# Generated by Django 6.0.8 on 2026-10-02 02:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0002_history_guards'),
        ('crm', '0006_name_transliteration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('waived', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_requirement', to='admissions.application')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateField()),
                ('institution_reference', models.CharField(max_length=120)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment', to='admissions.application')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JourneyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'year'), name='unique_journey_counter')],
            },
        ),
        migrations.CreateModel(
            name='OfferCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admissions.document')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracked_conditions', to='admissions.offerreceipt')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.JSONField(default=list)),
                ('accommodation', models.TextField(blank=True)),
                ('airport_pickup', models.CharField(blank=True, max_length=255)),
                ('flight_number', models.CharField(blank=True, max_length=40)),
                ('departure_at', models.DateTimeField(blank=True, null=True)),
                ('arrival_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='predeparture', to='admissions.application')),
            ],
        ),
        migrations.CreateModel(
            name='VisaCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=24, unique=True)),
                ('attempt_no', models.PositiveIntegerField()),
                ('state', models.CharField(default='PREPARING', max_length=30)),
                ('workflow_snapshot', models.JSONField(default=dict)),
                ('appointment_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visa_cases', to='admissions.application')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('previous_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='progression.visacase')),
            ],
        ),
        migrations.CreateModel(
            name='VisaBlocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocker', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='admissions.blocker')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_blockers', to='progression.visacase')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('holder', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('statement_on', models.DateField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admissions.document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_evidence', to='progression.visacase')),
            ],
        ),
        migrations.CreateModel(
            name='VisaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_documents', to='progression.visacase')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='admissions.document')),
            ],
        ),
        migrations.CreateModel(
            name='VisaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('old', models.JSONField(default=dict)),
                ('new', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='progression.visacase')),
            ],
        ),
        migrations.CreateModel(
            name='VisaWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=80)),
                ('version', models.PositiveIntegerField()),
                ('milestones', models.JSONField(default=list)),
                ('required_documents', models.JSONField(default=list)),
                ('predeparture_checklist', models.JSONField(default=list)),
                ('financial_evidence_required', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=120)),
                ('issued_on', models.DateField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ISSUED', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_documents', to='admissions.application')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admissions.document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('application', 'kind', 'number'), name='unique_enrollment_document')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=24, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('paid_on', models.DateField()),
                ('method', models.CharField(max_length=30)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('purpose', models.CharField(default='DEPOSIT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='admissions.application')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crm.person')),
                ('proof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admissions.document')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='visacase',
            constraint=models.UniqueConstraint(fields=('application', 'attempt_no'), name='unique_visa_attempt'),
        ),
        migrations.AddConstraint(
            model_name='visaworkflow',
            constraint=models.UniqueConstraint(fields=('country', 'version'), name='unique_visa_workflow_version'),
        ),
    ]
