# Generated by Django 6.0.8 on 2026-10-02 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('crm', '0006_name_transliteration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmessage',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='claimed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='dedupe_key',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='error_code',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='outboundmessage',
            name='provider_id',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='channelconsent',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('UNKNOWN', 'Unknown'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20),
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('trigger', models.CharField(choices=[('FOLLOWUP_DUE', 'FOLLOWUP_DUE'), ('TASK_DUE', 'TASK_DUE'), ('APPLICATION_DEADLINE', 'APPLICATION_DEADLINE'), ('APPLICATION_STATE', 'APPLICATION_STATE')], max_length=30)),
                ('student_messages', models.BooleanField(default=False)),
                ('staff_notifications', models.BooleanField(default=True)),
                ('advance_minutes', models.PositiveIntegerField(default=60)),
                ('enabled', models.BooleanField(default=False)),
                ('starts_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='communications.messagetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='LeadForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(max_length=100, unique=True)),
                ('page_id', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram')], max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.source')),
            ],
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='communications.outboundmessage')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=100, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='communications.leadform')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.person')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('event_key', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_key'), name='unique_communication_webhook')],
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=200)),
                ('outcome', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='communications.automationrule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rule', 'event_key'), name='unique_communication_automation')],
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS')], max_length=12)),
                ('sender', models.CharField(max_length=254)),
                ('body', models.TextField()),
                ('provider_id', models.CharField(max_length=200)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'provider_id'), name='unique_inbound_provider_message')],
            },
        ),
    ]
