# Generated by Django 6.0.8 on 2026-10-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_history_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('seen_at', models.DateTimeField()),
            ],
        ),
    ]
