# Generated by Django 6.0.8 on 2026-10-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_workerheartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageevent',
            name='estimated_cost_minor',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
