# Generated by Django 6.0.8 on 2026-10-01 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_lostreason_slarule_systempolicy_tag_activity_channel_and_more'),
        ('qr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=180, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict)),
                ('phone_e164', models.CharField(max_length=40)),
                ('channel_choice', models.CharField(default='SMS', max_length=20)),
                ('status', models.CharField(db_index=True, default='UNVERIFIED', max_length=20)),
                ('outcome', models.CharField(blank=True, max_length=20)),
                ('unverified_reason', models.CharField(default='NOT_ENTERED', max_length=30)),
                ('resume_token_hash', models.CharField(max_length=64)),
                ('resume_expires_at', models.DateTimeField()),
                ('ip_hash', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_via', models.CharField(blank=True, max_length=30)),
                ('corrections', models.PositiveIntegerField(default=0)),
                ('send_count', models.PositiveIntegerField(default=0)),
                ('purge_after', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.person')),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='qr.qrcode')),
                ('verified_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntakeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_ids', models.JSONField(default=list)),
                ('confidence', models.CharField(max_length=10)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='intake.intakesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_e164', models.CharField(max_length=40)),
                ('channel', models.CharField(max_length=20)),
                ('salt', models.CharField(max_length=40)),
                ('code_hash', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='intake.intakesubmission')),
            ],
        ),
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('channel', models.CharField(max_length=20)),
                ('to_hash', models.CharField(max_length=64)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('error', models.CharField(blank=True, max_length=60)),
                ('cost_minor', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='intake.otpchallenge')),
            ],
        ),
    ]
