# Generated by Django 6.0.8 on 2026-10-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=180)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
