'use client';
import {PhoneInput} from '@/components/phone-input';
import {useRef,useState,type FormEvent} from 'react';
import {api,ApiError,label,message,type Row} from '@/lib/api';
import {PasswordInput} from '@/components/password-input';
export type Field={name:string;label?:string;type?:string;required?:boolean;options?:{id:string|number;name:string}[];value?:unknown;help?:string};
export function ActionForm({title,path,fields,method='POST',extra={},done}:{title:string;path:string;fields:Field[];method?:string;extra?:Row;done:()=>void}) {
  const [contactType,setContactType]=useState(String(fields.find(f=>f.name==='type')?.value||'PHONE'));const [busy,setBusy]=useState(false),[error,setError]=useState('');const key=useRef('');
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const data:Row={...extra},fd=new FormData(e.currentTarget);try{for(const f of fields){const v=fd.get(f.name);if(f.type==='checkbox'){data[f.name]=v==='on';continue;}if(f.type==='multiselect'&&!fd.getAll(f.name).length){data[f.name]=[];continue;}if(v===''&&!f.required){if(f.value!==undefined)data[f.name]=['list','numbers'].includes(f.type||'')?[]:f.options||['date','number'].includes(f.type||'')?null:'';continue;}data[f.name]=f.type==='multiselect'?fd.getAll(f.name).map(Number):f.type==='list'?String(v).split(',').map(x=>x.trim()).filter(Boolean):f.type==='numbers'?String(v).split(',').map(x=>Number(x.trim())):f.type==='number'?Number(v):f.type==='datetime-local'?new Date(String(v)+'+05:45').toISOString():f.type==='json'?JSON.parse(String(v)):v;}const outgoing:Row=extra._nest?{...extra,[String(extra._nest)]:Object.fromEntries(Object.entries(data).filter(([k])=>!Object.keys(extra).includes(k)))}:data;if(extra._nest==='payload'&&data.reason){outgoing.reason=data.reason;delete (outgoing.payload as Row).reason;}if(extra._pair){outgoing.merged_id=(extra._pair as string[]).find(id=>id!==outgoing.survivor_id);delete outgoing._pair;}for(const k of Object.keys(data).filter(k=>k.startsWith('choice__'))){outgoing.field_choices={...((outgoing.field_choices||{}) as Row),[k.slice(8)]:data[k]};delete outgoing[k];}delete outgoing._nest;key.current ||=crypto.randomUUID();await api(path,method,outgoing,key.current);key.current='';done();}catch(e){setError(message(e));if(e instanceof ApiError)key.current='';}finally{setBusy(false);}}
  return <form className="inline-form" onSubmit={submit}><h3>{title}</h3><div className="form-grid">{fields.map(f=><label key={f.name} className={['textarea','json'].includes(f.type||'')?'span-2':undefined}>{f.label||label(f.name)}{f.options?<select onChange={e=>{if(f.name==='type')setContactType(e.target.value);}} name={f.name} multiple={f.type==='multiselect'} required={f.required} defaultValue={f.type==='multiselect'?((f.value||[]) as unknown[]).map(String):String(f.value??'')}><option value="">Choose…</option>{f.options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>:['textarea','json'].includes(f.type||'')?<textarea name={f.name} required={f.required} defaultValue={typeof f.value==='object'?JSON.stringify(f.value):String(f.value??'')}/>:(f.type==='tel'||['phone','mobile','whatsapp','guardian_contact'].includes(f.name)||(f.name==='raw_value'&&['PHONE','WHATSAPP'].includes(contactType)))?<PhoneInput key={f.name+contactType} name={f.name} label={f.label||label(f.name)} required={f.required} defaultValue={String(f.value??'')}/>:f.type==='password'||/password/i.test(f.name)?<PasswordInput name={f.name} required={f.required} defaultValue={String(f.value??'')} autoComplete="new-password"/>:<input name={f.name} type={['list','numbers'].includes(f.type||'')?'text':f.type||'text'} step={f.type==='number'?'any':undefined} required={f.required} defaultValue={f.type==='checkbox'?undefined:f.type==='datetime-local'&&f.value?new Date(new Date(String(f.value)).getTime()+345*60000).toISOString().slice(0,16):Array.isArray(f.value)?f.value.join(', '):String(f.value??'')} defaultChecked={f.type==='checkbox'?Boolean(f.value):undefined} maxLength={f.type==='text'||!f.type?500:undefined}/>} {f.help&&<small>{f.help}</small>}</label>)}</div>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save'}</button></form>;
}
export const choices=(values:string[])=>values.map(v=>({id:v,name:label(v)}));
export const reason:Field={name:'reason',type:'textarea',required:true,label:'Reason'};
