'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {api,date,label,message,type Row,type User,type Masters} from '@/lib/api';
import {Progression} from './progression';
import {ActionForm,choices,reason,type Field} from './action-form';

const states=['DRAFT','DOCUMENT_COLLECTION','READY','SUBMITTED','UNDER_ASSESSMENT','OFFER_RECEIVED'];
const terminal=['REJECTED','OFFER_DECLINED','OFFER_EXPIRED','WITHDRAWN','DEFERRED','CANCELLED'];
const kinds=['universities','campuses','courses','intakes','offerings','scholarships','workflows'];
const text=(r:Row,k:string)=>String(r[k]??'');
const rows=(r:Row,k:string)=>(r[k]||[]) as Row[];
type Form={title:string;path:string;fields:Field[];method?:string;extra?:Row};
type Catalog=Record<string,Row[]>;

export function Admissions({user,masters,personId,openPerson}:{user:User;masters:Masters;personId?:string;openPerson?:(id:string)=>Promise<void>}){
 const [tab,setTab]=useState('applications'),[catalog,setCatalog]=useState<Catalog>({}),[items,setItems]=useState<Row[]>([]),[summary,setSummary]=useState<Row>({}),[selected,setSelected]=useState<Row|null>(null),[form,setForm]=useState<Form|null>(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState(''),[offset,setOffset]=useState(0),[count,setCount]=useState(0),[loading,setLoading]=useState(true),[masterKind,setMasterKind]=useState('universities'),[preference,setPreference]=useState<Row|null>(null),[personChoice,setPersonChoice]=useState(personId||''),[people,setPeople]=useState<Row[]>([]),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 const editable=['ADMIN','MANAGER','COUNSELOR'].includes(user.role);
 const refresh=useCallback(async()=>{
  try{const [c,s]=await Promise.all([api<Catalog>('admissions/catalog/'),api<Row>('admissions/dashboard/')]);setCatalog(c);setSummary(s);
   const query=new URLSearchParams({search,state:filter,offset:String(offset),...(personId?{person_id:personId}:{})});
   const a=await api<Row>(`admissions/applications/?${query}`);setItems(rows(a,'results'));setCount(Number(a.count));
   setError('');
  }catch(e){setError(message(e));}finally{setLoading(false);}
 },[search,filter,offset,personId]);
 useEffect(()=>{const t=setTimeout(()=>void refresh(),250);return()=>clearTimeout(t);},[refresh]);
 useEffect(()=>{if(personId)return;api<Row>('people/?page=1').then(r=>setPeople(rows(r,'results'))).catch(e=>setError(message(e)));},[personId]);
 async function open(id:string){try{setSelected(await api<Row>(`admissions/applications/${id}/`));setForm(null);setError('');}catch(e){setError(message(e));}}
 async function done(){setBusy(true);try{setRevision(r=>r+1);setForm(null);await refresh();if(selected)await open(text(selected,'id'));if(preference&&personChoice)await match(personChoice);}finally{setBusy(false);}}
 async function match(id:string){if(!id)return;try{setPreference(await api<Row>(`admissions/preferences/${id}/`));setError('');}catch(e){setError(message(e));}}
 const edit=(title:string,path:string,fields:Field[],extra?:Row,method='POST')=>setForm({title,path,fields,extra,method});
 const options=(kind:string)=>(catalog[kind]||[]).filter(r=>r.active!==false).map(r=>({id:text(r,'id'),name:kind==='offerings'?offeringName(r):kind==='workflows'?`${r.destination} · Version ${r.version}`:text(r,'name')}));
 function offeringName(r:Row){const course=(catalog.courses||[]).find(c=>c.id===r.course),campus=(catalog.campuses||[]).find(c=>c.id===r.campus),intake=(catalog.intakes||[]).find(c=>c.id===r.intake);return `${course?.name||r.course} · ${campus?.name||r.campus} · ${intake?.name||r.intake} · ${r.currency} ${r.fee}`;}
 function newApp(offering?:string){edit('Create application','admissions/applications/',[...(!personId?[{name:'person_id',label:'Student / person',required:true,options:people.map(p=>({id:text(p,'id'),name:`${p.full_name} · ${p.ref}`})),value:personChoice}]:[]),{name:'offering_id',label:'Course, campus and intake',required:true,options:options('offerings'),value:offering},{name:'workflow_id',label:'Destination workflow',required:true,options:options('workflows')},{name:'notes',type:'textarea'}],personId?{person_id:personId}:undefined);}
 async function upload(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();setBusy(true);try{await api(`admissions/documents/${id}/`,'POST',new FormData(event.currentTarget));await done();}catch(e){setError(message(e));}finally{setBusy(false);}}
 const appBase=selected?`admissions/applications/${selected.id}/`:'';
 if(loading)return <section className="card empty">Loading admissions…</section>;
 return <section className="admissions-workspace">
  <div className="tabs">{['applications','deadlines','blockers','matching',...(user.role==='ADMIN'?['catalogue']:[])].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setSelected(null);setForm(null);if(t==='matching'&&personChoice)void match(personChoice);}}>{label(t)}</button>)}</div>
  {error&&<p className="error" role="alert">{error}</p>}
  {!personId&&<div className="metrics admissions-metrics">{[['Applications','applications'],['Documents to review','documents_for_review'],['Open blockers','open_blockers'],['Overdue deadlines','overdue_deadlines']].map(([title,key])=><div className="metric" key={key}><span>{title}</span><strong>{String(summary[key]||0)}</strong></div>)}</div>}
  {form&&<div className="card"><button className="text-button" onClick={()=>setForm(null)}>Close form</button><ActionForm key={form.title+form.path} {...form} done={()=>void done()}/></div>}
  {tab==='applications'&&!selected&&<section className="card"><div className="filters"><input aria-label="Search applications" placeholder="Search student, course or application…" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/><select aria-label="Application state" value={filter} onChange={e=>{setFilter(e.target.value);setOffset(0);}}><option value="">All states</option>{[...states,...terminal].map(s=><option key={s} value={s}>{label(s)}</option>)}</select>{editable&&<button className="primary" disabled={busy||!!form} onClick={()=>newApp()}>Create application</button>}</div>
   {!items.length&&<div className="empty"><h3>No applications yet</h3><p>Set up the catalogue, then create an application for a student from their profile.</p></div>}
   {items.map(a=><button className="admission-row" key={text(a,'id')} onClick={()=>void open(text(a,'id'))}><div><strong>{text(a,'ref')} · {text(a,'person_name')}</strong><p>{text(a,'course')} · {text(a,'university')} · {text(a,'intake')}</p><small>{text(a,'owner_name')} · Workflow version {text(a,'workflow_version')}</small></div><span className="badge">{label(text(a,'state'))}</span></button>)}
   <div className="card-footer"><span>{count} applications</span><button disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><button disabled={offset+50>=count} onClick={()=>setOffset(offset+50)}>Next</button></div>
  </section>}
  {tab==='applications'&&selected&&<section className="card application-detail"><button className="text-button" onClick={()=>{setSelected(null);setForm(null);}}>← All applications</button><h2>{text(selected,'ref')} · {text(selected,'person_name')}</h2><p>{text(selected,'course')} · {text(selected,'campus')} · {text(selected,'university')} · {text(selected,'intake')}</p><p><span className="badge">{label(text(selected,'state'))}</span> · {text(selected,'destination')} workflow version {text(selected,'workflow_version')}</p>
   {openPerson&&<button className="text-button" onClick={()=>void openPerson(text(selected,'person_id'))}>Open student profile</button>}
   <ol className="admission-milestones">{(selected.milestones as string[]).map(s=><li key={s} className={s===selected.state?'current':''}>{label(s)}</li>)}</ol>
   {selected.can_edit===true&&<div className="toolbar"><button className="secondary" disabled={busy||!!form} onClick={()=>edit('Update application',appBase,[{name:'state',options:choices([...new Set([...(selected.milestones as string[]),text(selected,'state'),...terminal])]),value:selected.state,required:true},{name:'notes',type:'textarea',value:selected.notes},{...reason,required:false,help:'Required for skipped, backward and terminal changes.'}],undefined,'PATCH')}>Update state / notes</button><button className="secondary" disabled={busy||!!form} onClick={()=>edit('Change course or defer intake',appBase,[{name:'offering_id',options:options('offerings'),required:true,value:selected.offering_id},reason],undefined,'PATCH')}>Change offering / deferral</button><button className="secondary" disabled={busy||!!form} onClick={()=>edit('Record offer',appBase+'offers/',[{name:'type',options:choices(['CONDITIONAL','UNCONDITIONAL']),value:'CONDITIONAL'},{name:'reference',label:'Institution offer reference'},{name:'conditions',type:'list',label:'Conditions (comma separated)'},{name:'expires_at',type:'datetime-local'},{name:'document_id',label:'Offer letter document',options:rows(selected,'documents').filter(d=>Number(d.version)>0).map(d=>({id:text(d,'id'),name:text(d,'title')}))}])}>Record offer</button>{['ADMIN','MANAGER'].includes(user.role)&&<button className="secondary" disabled={busy||!!form} onClick={()=>edit('Reassign application',appBase,[{name:'owner_id',options:masters.owners.filter(o=>o.branch_id===selected.branch_id),required:true,value:selected.owner_id},reason],undefined,'PATCH')}>Reassign owner</button>}</div>}
   <h3>Document checklist</h3><p>{selected.ready?'Required documents are complete and no blockers are open.':'Resolve required documents and blockers before Ready or Submitted.'}</p>
   {selected.can_documents===true&&<button className="secondary" disabled={busy||!!form} onClick={()=>edit('Request document','admissions/documents/',[{name:'type',required:true,label:'Document type'},{name:'title',required:true},{name:'required',type:'checkbox',value:true}],{person_id:selected.person_id,application_id:selected.id})}>Request document</button>}
   {rows(selected,'documents').map(d=><div className="record-card" key={text(d,'id')}><h4>{text(d,'title')} {d.required?'· Required':'· Optional'}</h4><p>{label(text(d,'status'))} · Version {text(d,'version')} {d.expires_at?`· Expires ${date(text(d,'expires_at'))}`:''}</p>
    {selected.can_documents===true&&<><form className="toolbar" onSubmit={e=>void upload(e,text(d,'id'))}><label>Upload a new version (PDF, PNG or JPEG, up to 5 MB)<input type="file" name="file" accept="application/pdf,image/png,image/jpeg" required/></label><button className="secondary" disabled={busy}>{busy?'Uploading…':'Upload'}</button></form><button className="text-button" disabled={busy||!!form} onClick={()=>edit('Review document',`admissions/documents/${d.id}/`,[{name:'status',options:choices(['REQUESTED','UNDER_REVIEW','VERIFIED','REJECTED','RESUBMISSION_REQUIRED','EXPIRED','WAIVED','NOT_APPLICABLE']),value:d.status},{name:'expires_at',type:'datetime-local'},{...reason,required:false,help:'A reason is required for rejection, waiver or not applicable.'}],undefined,'PATCH')}>Review / request resubmission</button></>}
    <div className="toolbar">{rows(d,'versions').map(v=><a className="secondary" key={text(v,'version')} href={`/api/v1/admissions/documents/${d.id}/versions/${v.version}/`}>Version {text(v,'version')} · {text(v,'filename')}</a>)}</div>
   </div>)}
   <h3>Offers</h3>{rows(selected,'offers').map(o=><div className="record-card" key={text(o,'id')}><strong>{label(text(o,'type'))} · {text(o,'reference')||'Institution offer'}</strong><p>{label(text(o,'status'))} {o.expires_at?`· Expires ${date(text(o,'expires_at'))}`:''}</p><ul>{(o.conditions as string[]).map((c,i)=><li key={i}>{c}</li>)}</ul>{selected.can_edit===true&&o.status==='RECEIVED'&&<button className="secondary" disabled={busy||!!form} onClick={()=>edit('Update offer',appBase+`offers/${o.id}/`,[{name:'status',options:choices(['DECLINED','EXPIRED']),required:true},reason],undefined,'PATCH')}>Decline / mark expired</button>}</div>)}
   <h3>Application deadlines</h3><Queue key={'deadlines'+revision} kind="deadlines" personId={text(selected,'person_id')} applicationId={text(selected,'id')} editable={selected.can_edit===true} edit={edit} masters={masters}/>
   <h3>Blockers</h3><Queue key={'blockers'+revision} kind="blockers" personId={text(selected,'person_id')} applicationId={text(selected,'id')} editable={selected.can_edit===true} edit={edit} masters={masters}/>
   <h3>Generated tasks</h3>{rows(selected,'tasks').map(t=><p key={text(t,'id')}>{text(t,'title')} · {label(text(t,'status'))} · {date(text(t,'due_at'))}</p>)}<p>Complete assigned tasks in the Tasks workspace.</p>
   <Progression application={selected} user={user} changed={done}/><h3>Application history</h3>{rows(selected,'events').map(e=><div className="record-card" key={text(e,'id')}><strong>{label(text(e,'type'))}</strong><p>{date(text(e,'created_at'))} {e.reason?`· ${e.reason}`:''}</p>{(e.new as Row)?.state? <p>{label(String((e.old as Row)?.state||''))} → {label(String((e.new as Row).state))}</p>:null}</div>)}
  </section>}
  {['deadlines','blockers'].includes(tab)&&<section className="card"><Queue key={tab+revision} kind={tab} personId={personId} editable={editable} edit={edit} masters={masters}/></section>}
  {tab==='matching'&&<section className="card"><h2>Student preferences and course matching</h2>{!personId&&<label>Choose a student<select value={personChoice} onChange={e=>{setPersonChoice(e.target.value);void match(e.target.value);}}><option value="">Choose…</option>{people.map(p=><option key={text(p,'id')} value={text(p,'id')}>{text(p,'full_name')} · {text(p,'ref')}</option>)}</select><small>Open a student profile to match any student outside this recent list.</small></label>}
   {preference&&<><p>Matches use academic results, English tests, preferences and published fees. Review institution requirements before applying.</p>{editable&&<button className="secondary" disabled={busy||!!form} onClick={()=>edit('Edit study preferences',`admissions/preferences/${personChoice}/`,[{name:'countries',type:'list',label:'Destinations (comma separated)',value:preference.countries},{name:'levels',type:'list',value:preference.levels},{name:'courses',type:'multiselect',options:options('courses'),value:preference.courses},{name:'intakes',type:'multiselect',options:options('intakes'),value:preference.intakes},{name:'maximum_fee',type:'number',value:preference.maximum_fee},{name:'currency',value:preference.currency,required:true},{name:'academic_percent',label:'Academic percentage',type:'number',value:preference.academic_percent},{name:'notes',type:'textarea',value:preference.notes}],undefined,'PATCH')}>Edit preferences</button>}
   {!rows(preference,'matches').length&&<p>No available course offerings. Ask the administrator to configure the catalogue.</p>}{rows(preference,'matches').map(m=><div className="record-card" key={text(m,'offering_id')}><h3>{text(m,'course')} · {text(m,'university')}</h3><p>{text(m,'country')} · {text(m,'intake')} · {text(m,'currency')} {text(m,'fee')} · <strong>{label(text(m,'result'))}</strong></p><ul>{['reasons','missing_information','mismatches'].flatMap(k=>(m[k] as string[]).map((v,i)=><li key={k+i}>{v}</li>))}</ul>{rows(m,'scholarships').map(s=><p key={text(s,'id')}>Scholarship: {text(s,'name')} · {text(s,'amount')} · {s.eligible===null?'Eligibility needs review':s.eligible?'Academic criteria met':'Academic criteria not met'} · {text(s,'eligibility')}</p>)}{editable&&<button className="secondary" disabled={busy||!!form} onClick={()=>newApp(text(m,'offering_id'))}>Create application for this offering</button>}</div>)}</>}
  </section>}
  {tab==='catalogue'&&<section className="card"><div className="toolbar"><select aria-label="Catalogue type" value={masterKind} onChange={e=>setMasterKind(e.target.value)}>{kinds.map(k=><option key={k} value={k}>{label(k)}</option>)}</select>{masterKind==='workflows'?<WorkflowEditor saved={()=>void refresh()}/>:<button className="primary" onClick={()=>edit(`Add ${({universities:'university',campuses:'campus',courses:'course',intakes:'intake',offerings:'offering',scholarships:'scholarship'} as Record<string,string>)[masterKind]}`,`admissions/catalog/${masterKind}/`,catalogFields(masterKind,catalog))}>Add record</button>}</div><p>Set up universities, campuses, courses and intakes before offerings. Applications keep the workflow version selected when created.</p>
   {(catalog[masterKind]||[]).map(r=><div className="record-card" key={text(r,'id')}><h3>{masterKind==='offerings'?offeringName(r):masterKind==='workflows'?`${r.destination} · Version ${r.version}`:text(r,'name')}</h3><p>{r.active===false?'Inactive':'Active'} {r.country?`· ${r.country}`:''} {r.level?`· ${r.level}`:''} {r.start_date?`· Starts ${r.start_date}`:''}</p>{masterKind==='workflows'?<><p>{(r.milestones as string[]).map(label).join(' → ')}</p><p>{rows(r,'required_documents').map(d=>text(d,'title')).join(', ')||'No required documents'}</p><button className="secondary" disabled={busy||!!form} onClick={()=>edit('Workflow availability',`admissions/catalog/workflows/${r.id}/`,[{name:'active',type:'checkbox',value:r.active}],undefined,'PATCH')}>Activate / deactivate</button></>:<button className="secondary" disabled={busy||!!form} onClick={()=>edit('Edit catalogue record',`admissions/catalog/${masterKind}/${r.id}/`,catalogFields(masterKind,catalog).map(f=>({...f,value:r[f.name]})),undefined,'PATCH')}>Edit</button>}</div>)}
  </section>}
 </section>;
}

function Queue({kind,personId,applicationId,editable,edit,masters}:{kind:string;personId?:string;applicationId?:string;editable:boolean;edit:(title:string,path:string,fields:Field[],extra?:Row,method?:string)=>void;masters:Masters}){
 const [items,setItems]=useState<Row[]>([]),[error,setError]=useState('');
 useEffect(()=>{api<Row>(`admissions/${kind}/?${new URLSearchParams({... (applicationId?{application_id:applicationId}:{}),... (personId?{person_id:personId}:{})})}`).then(r=>setItems(rows(r,'results').filter(r=>(!personId||String(r.person_id)===personId)&&(!applicationId||!r.application_id||String(r.application_id)===applicationId)))).catch(e=>setError(message(e)));},[kind,personId,applicationId]);
 const deadlines=kind==='deadlines';
 return <><h3>{deadlines?'Open deadlines':'Open blockers'}</h3>{error&&<p className="error">{error}</p>}{editable&&personId&&<button className="secondary" onClick={()=>edit(deadlines?'Add deadline':'Add blocker',`admissions/${kind}/`,deadlines?[{name:'type',options:choices(['APPLICATION','DOCUMENT','OFFER_EXPIRY','DEPOSIT','ENROLLMENT_DOC','VISA_APPOINTMENT','VISA_SUBMISSION','COURSE_START','PRE_DEPARTURE','FLIGHT']),value:'DOCUMENT'},{name:'title',required:true},{name:'due_at',type:'datetime-local',required:true}]:[{name:'type',required:true,value:'DOCUMENT'},{name:'description',type:'textarea',required:true},{name:'assigned_to_id',options:masters.users,required:true}],{person_id:personId,...(applicationId?{application_id:applicationId}:{})})}>Add {deadlines?'deadline':'blocker'}</button>}
 {!items.length&&<p>No open {kind}.</p>}{items.map(r=><div className="record-card" key={text(r,'id')}><strong>{deadlines?text(r,'title'):text(r,'type')}</strong><p>{text(r,'person_name')||text(r,'person__full_name')} {r.application_ref?`· ${r.application_ref}`:''}</p>{deadlines?<p className={r.overdue?'danger-text':''}>{date(text(r,'due_at'))} {r.overdue?'· Overdue':''}</p>:<p>{text(r,'description')}</p>}{editable&&<button className="secondary" onClick={()=>edit(deadlines?'Update deadline':'Resolve blocker',`admissions/${kind}/${r.id}/`,deadlines?[{name:'status',options:choices(['OPEN','COMPLETED','CANCELLED']),value:r.status},{name:'due_at',type:'datetime-local'},reason]:[reason],undefined,'PATCH')}>{deadlines?'Reschedule / complete':'Resolve'}</button>}</div>)}</>;
}

function catalogFields(kind:string,catalog:Catalog):Field[]{
 const select=(name:string,source:string):Field=>({name,required:true,options:(catalog[source]||[]).filter(r=>r.active!==false).map(r=>({id:text(r,'id'),name:text(r,'name')||`Offering ${r.id}`}))});
 const name:Field={name:'name',required:true},active:Field={name:'active',type:'checkbox',value:true};
 const fields:Record<string,Field[]>={universities:[name,{name:'country',required:true},{name:'website',type:'url'},active],campuses:[select('university','universities'),name,{name:'city'},{name:'address'},active],courses:[select('university','universities'),name,{name:'level',required:true},{name:'duration_months',type:'number',value:12},{name:'requirements',type:'textarea'},{name:'english_requirements',type:'textarea'},active],intakes:[name,{name:'start_date',type:'date',required:true},{name:'application_deadline',type:'datetime-local'},active],offerings:[select('course','courses'),select('campus','campuses'),select('intake','intakes'),{name:'fee',type:'number',value:0},{name:'currency',value:'USD',required:true},{name:'availability',options:choices(['OPEN','LIMITED','CLOSED']),value:'OPEN'},{name:'requirements',type:'textarea'},{name:'english_test',options:choices(['IELTS','PTE','TOEFL','DUOLINGO','OTHER'])},{name:'minimum_english_score',type:'number'},{name:'minimum_academic_percent',type:'number'},active],scholarships:[select('offering','offerings'),name,{name:'amount',type:'number',value:0},{name:'eligibility',type:'textarea'},{name:'minimum_academic_percent',type:'number'},{name:'deadline',type:'datetime-local'},active]};return fields[kind]||[];
}

function WorkflowEditor({saved}:{saved:()=>void}){
 const [show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const data=new FormData(event.currentTarget),lines=(key:string)=>String(data.get(key)||'').split('\n').map(x=>x.trim()).filter(Boolean);try{await api('admissions/catalog/workflows/','POST',{destination:data.get('destination'),milestones:lines('milestones').map(s=>s.toUpperCase().replaceAll(' ','_')),required_documents:lines('documents').map((title,i)=>({type:`DOC_${i+1}`,title,required:true})),offer_conditions:lines('conditions'),enrollment_requirements:lines('enrollment'),visa_requirements:lines('visa'),task_templates:{DRAFT:lines('draft_tasks'),SUBMITTED:lines('submitted_tasks')}});setShow(false);setError('');saved();}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <><button className="primary" onClick={()=>setShow(!show)}>Create workflow version</button>{show&&<form className="inline-form" onSubmit={e=>void submit(e)}><h3>Destination workflow</h3><p>A new version keeps existing applications unchanged.</p><label>Destination country<input name="destination" required maxLength={80}/></label><label>Milestones in order (one per line)<textarea name="milestones" defaultValue={states.map(label).join('\n')} required/></label><small>Begin with Draft and end with Offer received.</small><div className="form-grid">{[['documents','Required document titles'],['conditions','Typical offer conditions'],['enrollment','Enrollment requirements'],['visa','Visa requirements'],['draft_tasks','Tasks when application is created'],['submitted_tasks','Tasks after submission']].map(([key,title])=><label key={key}>{title}<textarea name={key} placeholder="One item per line"/></label>)}</div>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save new version'}</button></form>}</>;
}
