'use client';
import {useEffect,useState,useRef} from 'react';
import {api,date,type Detail,type User} from '@/lib/api';
import {ActionForm,choices} from './action-form';

type Row=Record<string,unknown>;
export function Communications({detail,user}:{detail:Detail;user:User}){
 const [history,setHistory]=useState<{consents:Row[];messages:Row[];incoming:Row[];has_more?:boolean}>({consents:[],messages:[],incoming:[]});
 const [preview,setPreview]=useState<{subject:string;body:string}|null>(null),[review,setReview]=useState<{id:unknown;action:string}|null>(null);
 const [templates,setTemplates]=useState<Row[]>([]),[error,setError]=useState(''),[form,setForm]=useState<'consent'|'template'|'queue'|null>(null),[busy,setBusy]=useState(false);
 const [offset,setOffset]=useState(0);const offsetRef=useRef(0);offsetRef.current=offset;
 const path=`communications/people/${detail.person.id}/`;
 async function load(){try{const [h,t]=await Promise.all([api<typeof history>(path),api<{results:Row[]}>('communications/templates/')]);setHistory(h);setOffset(0);setTemplates(t.results);}catch(e){setError(e instanceof Error?e.message:'Could not load communications.');}}
 useEffect(()=>{void load();const timer=setInterval(()=>{if(!offsetRef.current)void load();},30000);return()=>clearInterval(timer);},[path]);
 async function older(){try{const next=offset+100;const h=await api<typeof history>(`${path}?offset=${next}`);setHistory(current=>({...h,messages:[...current.messages,...h.messages.filter(m=>!current.messages.some(x=>x.id===m.id))],incoming:[...current.incoming,...h.incoming.filter(m=>!current.incoming.some(x=>x.id===m.id))]}));setOffset(next);}catch(e){setError(e instanceof Error?e.message:'Could not load older messages.');}}
 async function cancel(id:unknown){setBusy(true);try{await api(path,'POST',{action:'cancel',message_id:id});await load();}catch(e){setError(e instanceof Error?e.message:'Could not cancel message.');}finally{setBusy(false);}}
 const channel={name:'channel',options:choices(['EMAIL','WHATSAPP','SMS']),required:true};
 const fields=form==='template'?[{name:'name',required:true},channel,{name:'subject'},{name:'body',type:'textarea',required:true}]:form==='consent'?[channel,{name:'allowed',label:'Permission',options:[{id:'true',name:'Consent given'},{id:'false',name:'Opt out'}],required:true},{name:'evidence',label:'Consent source / evidence',type:'textarea',required:true}]:[{name:'template_id',label:'Template',options:templates.map(t=>({id:String(t.id),name:`${t.name} · ${t.channel} · v${t.version}`})),required:true},{name:'contact_id',label:'Verified recipient',options:detail.contacts.filter(c=>c.verified_at).map(c=>({id:String(c.id),name:`${c.type} · ${c.raw_value}`})),required:true},{name:'scheduled_at',type:'datetime-local',label:'Schedule (leave blank for now)'}];
 const conversation=[...history.incoming.map((m):Row=>({...m,direction:'Incoming'})),...history.messages.map((m):Row=>({...m,direction:'Outgoing'}))].sort((a,b)=>new Date(String(b.received_at||b.created_at)).getTime()-new Date(String(a.received_at||a.created_at)).getTime());
 return <section className="card"><h3>Communications</h3><p className="muted">Messages require verified contacts and explicit channel consent. Delivery requires a configured provider and running communication workers.</p>{error&&<p className="error" role="alert">{error}</p>}
 <div className="profile-actions"><button className="secondary" onClick={()=>void load()}>Refresh conversation</button>{user.permissions?.communication_send&&<><button className="secondary" onClick={()=>setForm('consent')}>Record consent / opt out</button><button className="secondary" onClick={()=>setForm('queue')}>Queue message</button></>}{user.permissions?.communication_templates&&<button className="secondary" onClick={()=>setForm('template')}>Create template version</button>}</div>
 {['EMAIL','WHATSAPP','SMS'].map(c=>{const consent=history.consents.find(r=>r.channel===c);return <p key={c}>{c}: {consent?.allowed?'Consent given':consent?'Opted out':'No explicit consent'}</p>;})}
 {conversation.map(m=><article className="card" key={String(m.id)}><strong>{String(m.direction)} {String(m.channel)} {m.status?`· ${m.status}`:''}</strong><p>{String(m.sender||m.recipient)} · {date(String(m.received_at||m.created_at))}</p>{!!m.subject&&<h4>{String(m.subject)}</h4>}<p style={{whiteSpace:'pre-wrap'}}>{String(m.body)}</p>{!!m.error_code&&<p className="error">{String(m.error_code)}</p>}{(m.events as Row[]||[]).map((e,i)=><small key={i}>{String(e.status)} {String(e.detail)} · {date(String(e.created_at))}<br/></small>)}{user.permissions?.communication_send&&m.status==='FAILED'&&<button className="secondary" onClick={()=>setReview({id:m.id,action:'retry'})}>Retry failed message</button>}{user.permissions?.communication_templates&&m.status==='UNKNOWN'&&<button className="secondary" onClick={()=>setReview({id:m.id,action:'message_reconcile'})}>Review uncertain delivery</button>}{user.permissions?.communication_send&&m.status==='QUEUED'&&<button className="secondary" disabled={busy} onClick={()=>void cancel(m.id)}>Cancel queued message</button>}</article>)}
 {history.has_more&&<button className="secondary" onClick={()=>void older()}>Load older messages</button>}{form&&<button className="secondary" onClick={()=>setForm(null)}>Close communication form</button>}{form&&<div onChange={event=>{const target=event.target;if(!(target instanceof HTMLSelectElement))return;if(target.name==='template_id'&&target.value)void api<{subject:string;body:string}>(path,'POST',{action:'preview',template_id:target.value}).then(setPreview).catch(e=>setError(e instanceof Error?e.message:'Preview failed.'));}}><ActionForm key={form} title={form==='template'?'Create communication template':form==='consent'?'Record channel permission':'Queue student message'} fields={fields} path={form==='template'?'communications/templates/':path} extra={{action:form==='consent'?'consent':'queue'}} done={()=>{setForm(null);setPreview(null);void load();}}/></div>}{form==='queue'&&preview&&<article className="card"><h4>Message preview</h4><strong>{preview.subject}</strong><p style={{whiteSpace:'pre-wrap'}}>{preview.body}</p></article>}{review&&<div><button className="secondary" onClick={()=>setReview(null)}>Close message review</button><ActionForm title={review.action==='retry'?'Retry confirmed failed message':'Reconcile uncertain delivery'} path={review.action==='retry'?path:'communications/workspace/'} fields={[...(review.action==='message_reconcile'?[{name:'status',options:choices(['SENT','FAILED']),required:true}]:[]),{name:'reason',type:'textarea',required:true}]} extra={{action:review.action,id:review.id,message_id:review.id}} done={()=>{setReview(null);void load();}}/></div>}</section>;
}
