'use client';
import {useEffect,useState} from 'react';
import {api,type Row,message,type Person,label} from '@/lib/api';
import {ActionForm,choices,reason,type Field} from './action-form';

export function CommunicationSettings(){
 const [personSearch,setPersonSearch]=useState(''),[people,setPeople]=useState<Person[]>([]);
 const [data,setData]=useState<Row>({}),[error,setError]=useState(''),[form,setForm]=useState<{title:string;fields:Field[];extra:Row}|null>(null);
 const list=(key:string)=>(data[key]||[]) as Row[];
 async function load(){try{setData(await api<Row>('communications/workspace/'));}catch(e){setError(message(e));}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer);},[]);
 const options=(key:string)=>list(key).map(r=>({id:String(r.id),name:String(r.name)}));
 function edit(title:string,fields:Field[],extra:Row){setForm({title,fields,extra});}
 async function searchPeople(){try{const result=await api<{results:Person[]}>(`people/?search=${encodeURIComponent(personSearch)}`);setPeople(result.results);}catch(e){setError(message(e));}}
 const person:Field={name:'person_id',label:'Existing person',options:people.map(p=>({id:p.id,name:`${p.full_name} · ${p.ref}`}))};
 const branch:Field={name:'branch_id',label:'Branch',options:options('branches'),required:true};
 return <section><h2>Communications & automation</h2><p className="muted">Provider credentials are configured privately on the server. Enable rules only after checking templates, consent and worker connectivity.</p>{error&&<p className="error" role="alert">{error}</p>}
 <div className="form-grid">{Object.entries((data.providers||{}) as Record<string,boolean>).map(([channel,ready])=><article className="card" key={channel}><h3>{channel}</h3><p>{ready?'Provider configured':'Provider not configured'}</p></article>)}</div><p>Worker: {data.worker_healthy?'Active':'No recent heartbeat'}{data.worker_seen_at?` · Last seen ${new Date(String(data.worker_seen_at)).toLocaleString()}`:''}</p>
 <div className="profile-actions"><button className="primary" disabled={!list('branches').length} onClick={()=>edit('Create reminder rule',[{name:'name',required:true},branch,{name:'trigger',options:choices(['FOLLOWUP_DUE','TASK_DUE','APPLICATION_DEADLINE','APPLICATION_STATE']),required:true},{name:'template_id',label:'Student template',options:list('templates').map(t=>({id:String(t.id),name:`${t.name} (${t.channel}, v${t.version})`}))},{name:'student_messages',label:'Message students with channel consent',type:'checkbox'},{name:'staff_notifications',label:'Notify assigned staff in the workspace',type:'checkbox',value:true},{name:'advance_minutes',label:'Minutes before due time',type:'number',value:60,required:true}],{action:'rule_create'})}>Create reminder rule</button><button className="secondary" disabled={!list('branches').length||!list('sources').length} onClick={()=>edit('Connect lead form',[{name:'name',required:true},{name:'platform',options:choices(['FACEBOOK','INSTAGRAM']),required:true},{name:'page_id',label:'Page ID',required:true},{name:'form_id',label:'Lead form ID',required:true},branch,{name:'source_id',label:'Lead source',options:options('sources'),required:true}],{action:'form_create'})}>Connect Facebook / Instagram form</button></div>
 {form&&<div className="card">{form.fields.some(f=>f.name==='person_id')&&<div><label>Find existing person<input value={personSearch} onChange={e=>setPersonSearch(e.target.value)}/></label><button className="secondary" onClick={()=>void searchPeople()}>Search people</button></div>}<button className="secondary" onClick={()=>setForm(null)}>Close communication form</button><ActionForm title={form.title} fields={form.fields.map(f=>f.name==='person_id'?{...f,options:person.options}:f)} extra={form.extra} path="communications/workspace/" done={()=>{setForm(null);void load();}}/></div>}
 <h3>Outbound queue</h3>{list('outbound_stats').map(r=><p key={String(r.status)}>{String(r.status)}: {String(r.count)}</p>)}{list('uncertain').map(r=><article className="card" key={String(r.id)}><strong>{String(r.person__full_name)} · {String(r.channel)}</strong><p>{String(r.recipient)} · {String(r.error_code)}</p><p>{String(r.body)}</p><button className="secondary" onClick={()=>edit('Reconcile uncertain delivery',[{name:'status',options:choices(['SENT','FAILED']),required:true},{name:'provider_id',label:'Confirmed provider message ID (if available)'},reason],{action:'message_reconcile',id:r.id})}>Review delivery</button></article>)}<h3>Reminder rules</h3>{list('rules').map(r=><article className="card" key={String(r.id)}><strong>{String(r.name)}</strong><p>{String(r.trigger)} · {r.enabled?'Enabled':'Disabled'}</p><button className="secondary" onClick={()=>edit(r.enabled?'Disable reminder':'Enable reminder',[reason],{action:'rule_toggle',id:r.id,enabled:!r.enabled})}>{r.enabled?'Disable':'Enable'}</button></article>)}
 <h3>Lead forms</h3>{list('forms').map(r=><article className="card" key={String(r.id)}><strong>{String(r.name)} · {String(r.platform)}</strong><p>{r.enabled?'Enabled':'Disabled'}</p><button className="secondary" onClick={()=>edit(r.enabled?'Disable lead sync':'Enable lead sync',[reason],{action:'form_toggle',id:r.id,enabled:!r.enabled})}>{r.enabled?'Disable':'Enable'}</button></article>)}
 <h3>Social lead review</h3>{list('leads').map(r=><article className="card" key={String(r.id)}><strong>Lead {String(r.lead_id)} · {String(r.status)}</strong>{((r.payload as Row)?.field_data as {name:string;values:string[]}[]||[]).map((field,i)=><p key={i}>{label(field.name)}: {field.values.join(', ')}</p>)}{!!r.error_code&&<p className="error">{String(r.error_code)}</p>}{r.status==='PENDING'&&Number(r.attempts)>=5&&<button className="secondary" onClick={()=>edit('Retrieve lead again',[reason],{action:'lead_retry',id:r.id})}>Retry retrieval</button>}{r.status==='REVIEW'&&<><button className="primary" onClick={()=>edit('Approve reviewed lead',[{name:'person_id',label:'Existing person (required for a potential duplicate)',help:'Leave blank to create a new person with no duplicate signals.'},reason],{action:'lead_review',id:r.id})}>Approve / link person</button><button className="secondary" onClick={()=>edit('Reject lead',[reason],{action:'lead_review',id:r.id,reject:true})}>Reject</button></>}</article>)}
 <h3>Incoming messages needing identification</h3>{list('unmatched').map(r=><article className="card" key={String(r.id)}><strong>{String(r.channel)} · {String(r.sender)}</strong><p style={{whiteSpace:'pre-wrap'}}>{String(r.body)}</p><button className="secondary" onClick={()=>edit('Identify incoming message',[{name:'person_id',label:'Matching person',required:true},reason],{action:'inbound_match',id:r.id})}>Match to person</button></article>)}
 <h3>Recent automation results</h3>{list('runs').map(r=><p key={String(r.id)}>Rule {String(r.rule_id)}: {String(r.outcome)}</p>)}
 <h3>Webhook processing</h3>{list('webhooks').map(r=><article className="card" key={String(r.id)}><strong>{String(r.provider)} · {String(r.status)}</strong><p>Attempts: {String(r.attempts)} {String(r.error_code)}</p>{r.status!=='PROCESSED'&&Number(r.attempts)>=10&&<button className="secondary" onClick={()=>edit('Retry webhook',[reason],{action:'webhook_retry',id:r.id})}>Retry processing</button>}</article>)}
 </section>;
}
