 'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {CounselingOptionInput} from './counseling-option-input';
import {api,date,message,type Row} from '@/lib/api';
export function CounselingSuggestions({personId,editable,saved}:{personId:string;editable:boolean;saved:(message:string)=>Promise<void>}){
 const [rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[count,setCount]=useState(1);const pending=useRef({body:'',key:''}),path=`people/${personId}/counseling/suggestions/`;
 async function load(){try{const result=await api<{results:Row[]}>(path);setRows(result.results);}catch(e){setError(message(e));}}
 useEffect(()=>{void load();},[path]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),data={suggestions:Array.from({length:count},(_,index)=>Object.fromEntries(['country','study_level','university','course','intake','notes'].map(name=>[name,fd.get(`${index}_${name}`)||''])))},body=JSON.stringify(data);if(pending.current.body!==body)pending.current={body,key:crypto.randomUUID()};setBusy(true);setError('');try{await api(path,'POST',data,pending.current.key);pending.current={body:'',key:''};setOpen(false);setCount(1);await load();await saved('Study suggestion added to history.');}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <section className="card record-card suggestion-history"><div className="card-heading"><div><h2>Suggested study options</h2><p>Earlier recommendations stay here with the counselor and date.</p></div>{editable&&<button className="secondary" onClick={()=>setOpen(!open)}>{open?'Cancel':'Add suggestion'}</button>}</div>{error&&<p className="error" role="alert">{error}</p>}{open&&<form className="inline-form" onSubmit={submit}><>{Array.from({length:count},(_,index)=><fieldset key={index}><legend>Suggestion {index+1}</legend><div className="form-grid"><CounselingOptionInput kind="COUNTRY" name={`${index}_country`} label="Suggested country *" maxLength={80} required/><label>Study level<select name={`${index}_study_level`}><option value="">Not specified</option>{['Diploma','Bachelor','Master','Mres','PhD','Language course','Other'].map(x=><option key={x}>{x}</option>)}</select></label><CounselingOptionInput kind="UNIVERSITY" name={`${index}_university`} label="University / college"/><CounselingOptionInput kind="COURSE" name={`${index}_course`} label="Course / program"/><CounselingOptionInput kind="INTAKE" name={`${index}_intake`} label="Intake" maxLength={80}/><label className="span-2">Why suggested / discussion notes<textarea name={`${index}_notes`} rows={3} maxLength={5000}/></label></div></fieldset>)}</><div className="toolbar"><button className="secondary" type="button" disabled={busy||count>=20} onClick={()=>setCount(n=>n+1)}>Add another university / course</button>{count>1&&<button className="secondary" type="button" disabled={busy} onClick={()=>setCount(n=>n-1)}>Remove last suggestion</button>}</div><button className="primary" disabled={busy}>{busy?'Saving…':'Save suggestion to history'}</button></form>}{rows.length?rows.map(row=><article className="study-suggestion" key={String(row.id)}><h3>{String(row.country)}{row.study_level?' · '+String(row.study_level):''}</h3><dl className="data-fields">{[['university','University / college'],['course','Course / program'],['intake','Intake']].map(([key,label])=><div key={key}><dt>{label}</dt><dd>{String(row[key]||'Not specified')}</dd></div>)}</dl>{Boolean(row.notes)&&<p style={{whiteSpace:'pre-wrap'}}>{String(row.notes)}</p>}<small>Suggested by {String(row.suggested_by)} · {date(String(row.created_at))}</small></article>):<p>No study options suggested yet.</p>}</section>;
}
