 'use client';
import {useEffect,useId,useRef,useState} from 'react';
import {callingCodes} from '@/lib/calling-codes';
import {api,message} from '@/lib/api';
type Option={id:number;name:string;kind:string};
export function CounselingOptionInput({kind,name,label,maxLength=200,required=false}:{kind:'COUNTRY'|'UNIVERSITY'|'COURSE'|'INTAKE';name:string;label:string;maxLength?:number;required?:boolean}){
 const [options,setOptions]=useState<Option[]>([]),[value,setValue]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[active,setActive]=useState(-1);const id=useId(),root=useRef<HTMLDivElement>(null);
 async function load(){try{const r=await api<{results:Option[]}>(`counseling/options/?kind=${kind}`);const names=new Intl.DisplayNames(['en'],{type:'region'});const defaults:Option[]=kind==='COUNTRY'?Object.keys(callingCodes).map((code,index)=>({id:-index-1,kind,name:names.of(code)||code})):[];setOptions([...r.results,...defaults.filter(o=>!r.results.some(saved=>saved.name.toLowerCase()===o.name.toLowerCase()))].sort((a,b)=>a.name.localeCompare(b.name)));}catch(e){setError(message(e));}}
 useEffect(()=>{void load();const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};const changed=()=>void load();document.addEventListener('pointerdown',outside);window.addEventListener('consman-options-updated',changed);return()=>{document.removeEventListener('pointerdown',outside);window.removeEventListener('consman-options-updated',changed);};},[kind]);
 const query=value.trim(),matches=options.filter(o=>o.name.toLowerCase().includes(query.toLowerCase())).slice(0,30),exact=options.some(o=>o.name.toLowerCase()===query.toLowerCase());
 function choose(option:Option){setValue(option.name);setOpen(false);setActive(-1);setError('');}
 async function add(){if(!query||busy)return;setBusy(true);setError('');try{const option=await api<Option>('counseling/options/','POST',{kind,name:query});setOptions(current=>[...current.filter(o=>o.id!==option.id),option]);choose(option);window.dispatchEvent(new Event('consman-options-updated'));}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <div className="catalog-input" ref={root}><label htmlFor={id}>{label}</label><input id={id} name={name} required={required} value={value} maxLength={maxLength} autoComplete="off" role="combobox" aria-expanded={open} aria-controls={id+'-options'} aria-autocomplete="list" aria-activedescendant={active>=0&&matches[active]?`${id}-option-${matches[active].id}`:undefined} placeholder="Search or add new…" onFocus={()=>setOpen(true)} onBlur={e=>{if(!root.current?.contains(e.relatedTarget as Node))setOpen(false);}} onChange={e=>{setValue(e.target.value);setOpen(true);setActive(-1);}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);setActive(-1);}if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive(i=>Math.min(i+1,matches.length-1));}if(e.key==='ArrowUp'){e.preventDefault();setActive(i=>Math.max(0,i-1));}if(e.key==='Enter'&&open){e.preventDefault();if(active>=0&&matches[active])choose(matches[active]);else if(query&&!exact)void add();else setOpen(false);}}}/>{open&&<div className="catalog-menu"><div id={id+'-options'} role="listbox" aria-label={label}>{matches.map((o,index)=><button type="button" role="option" aria-selected={index===active} id={`${id}-option-${o.id}`} key={o.id} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(o)}>{o.name}</button>)}</div>{!matches.length&&<p>No matching {label.toLowerCase()} found.</p>}{query&&!exact&&<button className="catalog-add" type="button" disabled={busy} onMouseDown={e=>e.preventDefault()} onClick={()=>void add()}>{busy?'Adding…':`Add “${query}”`}</button>}{!query&&!options.length&&<p>Type a name to add the first option.</p>}</div>}{error&&<p className="error" role="alert">{error}</p>}</div>;
}
