'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import QRCode from 'qrcode';
import {ProfileDocuments} from './profile-documents';
import {CounselingSuggestions} from './counseling-suggestions';
import {api,date,message,type Detail,type Masters,type Row,type User} from '@/lib/api';
import {PhoneInput} from './phone-input';
const types=['Passport','Academic Transcripts','Certificates','Citizenship / ID','English Test Score','CV / Resume','Financial Documents','Photographs','Recommendation Letters','Experience Letters','Medical / Police Report','Other'];
export function CounselingRecord({detail,user,masters,saved}:{detail:Detail;user:User;masters:Masters;saved:(m:string)=>Promise<void>}){
 const [record,setRecord]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[phone,setPhone]=useState(''),[qr,setQr]=useState('');
 const requestKey=useRef({body:'',key:''});
 const path=`people/${detail.person.id}/counseling/`,editable=!!user.permissions?.counseling;
 async function load(){try{const r=await api<Row>(path);setRecord(r);}catch(e){setError(message(e));}}
 useEffect(()=>{void load();},[path]);
 useEffect(()=>{let active=true;setQr('');if(phone&&phone.replace(/\D/g,'').length>=8)QRCode.toDataURL(`https://wa.me/${phone.replace(/\D/g,'')}`,{width:256,margin:4}).then(url=>{if(active)setQr(url);});return()=>{active=false;};},[phone]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),data:Row={};for(const key of ['summary','decisions','pending_documents','next_step','service_taken','remarks'])data[key]=fd.get(key)||'';data.documents_checklist=fd.getAll('documents_checklist');for(const key of ['followup_due_at','scanning_due_at'])if(fd.get(key))data[key]=new Date(String(fd.get(key))+'+05:45').toISOString();for(const key of ['followup_owner_id','scanning_owner_id'])if(fd.get(key))data[key]=Number(fd.get(key));data.followup_method=fd.get('followup_method')||'CALL';data.followup_notes=fd.get('followup_notes')||'';setBusy(true);setError('');try{const body=JSON.stringify(data);if(requestKey.current.body!==body)requestKey.current={body,key:crypto.randomUUID()};await api(path,'POST',data,requestKey.current.key);requestKey.current={body:'',key:''};await load();await saved('Counseling record saved.');}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <><CounselingSuggestions personId={detail.person.id} editable={editable} saved={saved}/><section className="card record-card"><h2>Counseling and frontdesk handoff</h2><p>Assigned counselor: {detail.person.owner_name}. Use Lifecycle / priority above to mark the lead status and Hot, Warm or Cold priority. Document uploads are optional.</p>{error&&<p className="error" role="alert">{error}</p>}{record&&<form key={String(record.updated_at||'new')} onSubmit={submit}><fieldset disabled={!editable||busy}><div className="form-grid">{[['summary','Key discussion / student profile summary'],['decisions','Key decisions'],['pending_documents','Documents pending'],['next_step','Next step'],['service_taken','Package / service taken'],['remarks','Staff remarks']].map(([name,title])=><label key={name} className="span-2">{title}{['next_step','service_taken'].includes(name)?<input name={name} maxLength={200} defaultValue={String(record[name]||'')}/>:<textarea name={name} maxLength={name==='summary'||name==='decisions'?10000:5000} defaultValue={String(record[name]||'')} rows={3}/>}</label>)}<fieldset className="span-2"><legend>Documents checklist</legend><div className="form-grid">{types.map(type=><label className="checkbox" key={type}><input type="checkbox" name="documents_checklist" value={type} defaultChecked={(record.documents_checklist as string[]).includes(type)}/>{type}</label>)}</div></fieldset>{editable&&<><h3 className="span-2">Schedule the next follow-up</h3><label>Follow-up date<input name="followup_due_at" type="datetime-local"/></label><label>Follow-up by<select name="followup_method">{['CALL','WHATSAPP','EMAIL','MEETING'].map(x=><option key={x}>{x}</option>)}</select></label><label>Assigned caller / frontdesk / counselor<select name="followup_owner_id" defaultValue=""><option value="">Myself</option>{masters.users.filter(u=>u.branch_id===detail.person.branch&&['ADMIN','MANAGER','COUNSELOR','FRONTDESK'].includes(String(u.role))).map(u=><option key={u.id} value={u.id}>{u.name} · {String(u.role)}</option>)}</select></label><label className="span-2">What should the caller discuss?<textarea name="followup_notes" rows={3} maxLength={5000} placeholder="Discuss pending transcripts, explain the UK intake deadline, and confirm the next visit."/></label><h3 className="span-2">Send physical documents for scanning (optional)</h3><label>Frontdesk officer<select name="scanning_owner_id" defaultValue=""><option value="">No scanning handoff</option>{masters.users.filter(u=>u.branch_id===detail.person.branch&&u.role==='FRONTDESK').map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Scanning due<input name="scanning_due_at" type="datetime-local"/></label></>}</div></fieldset>{editable&&<button className="primary" disabled={busy}>Save counseling and handoff</button>}</form>}{Boolean(record?.updated_at)&&<p className="muted">Updated by {String(record?.updated_by)} · {date(String(record?.updated_at))}</p>}
 <ProfileDocuments personId={detail.person.id} canUpload={!!user.permissions?.edit} saved={saved}/>
 {editable&&<details><summary>Show my WhatsApp QR to the student</summary><p>Enter the office or counselor number where the student should send their documents.</p><PhoneInput value={phone} onChange={setPhone} label="Counselor WhatsApp number"/>{qr&&<><img src={qr} width={256} height={256} alt="Scan to message the counselor on WhatsApp"/><a className="secondary" href={qr} download="counselor-whatsapp.png">Download WhatsApp QR</a></>}</details>}</section></>;
}
