'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {api,label,date,message,type Row} from '@/lib/api';
import {ActionForm,choices,reason,type Field} from './action-form';
const text=(r:Row,key:string)=>String(r[key]??''),rows=(r:Row,key:string)=>(r[key]||[]) as Row[];
const sections=['overview','invoices','payments','receipts','expenses','commissions','commission_receipts','rules'];
type Form={title:string;fields:Field[];extra:Row};

export function Finance(){
 const [section,setSection]=useState('overview'),[data,setData]=useState<Row|null>(null),[selected,setSelected]=useState<Row|null>(null),[history,setHistory]=useState<Row[]>([]),[form,setForm]=useState<Form|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[offset,setOffset]=useState(0),[search,setSearch]=useState(''),[status,setStatus]=useState('');
 const kind=section==='overview'?'invoices':section;
 const query=new URLSearchParams({kind,offset:String(offset),search,status});
 const refresh=useCallback(async()=>{try{const result=await api<Row>(`finance/?${new URLSearchParams({kind,offset:String(offset),search,status})}`);setData(result);setError('');return result;}catch(e){setError(message(e));}},[kind,offset,search,status]);
 useEffect(()=>{const timer=setTimeout(()=>void refresh(),200);return()=>clearTimeout(timer);},[refresh]);
 const edit=(title:string,action:string,fields:Field[],extra:Row={})=>{setForm({title,fields,extra:{action,...extra}});setSelected(null);};
 async function done(){setBusy(true);setForm(null);setSelected(null);try{await refresh();}finally{setBusy(false);}}
 async function open(record:Row){setSelected(record);setForm(null);try{const result=await api<Row>(`finance/${kind}/${record.id}/events/`);setHistory(rows(result,'results'));}catch(e){setError(message(e));}}
 async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setBusy(true);try{await api(`finance/${kind}/${selected.id}/proof/`,'POST',new FormData(event.currentTarget));await done();}catch(e){setError(message(e));}finally{setBusy(false);}}
 if(!data)return <section className="card"><p>{error||'Loading finance…'}</p></section>;
 const editable=data.can_edit===true,locked=busy||!!form,people=rows(data,'people').map(p=>({id:text(p,'id'),name:`${p.full_name} · ${p.ref}`})),apps=rows(data,'applications').map(a=>({id:text(a,'id'),name:`${a.ref} · ${a.person__full_name}`})),institutions=rows(data,'institutions').map(u=>({id:text(u,'id'),name:text(u,'name')})),rules=rows(data,'rules').map(r=>({id:text(r,'id'),name:`${r.institution_name} · ${r.name} · v${r.version} · ${r.method} ${r.value} ${r.currency}`}));
 const amount:Field={name:'amount',type:'number',required:true},currency:Field={name:'currency',value:'NPR',required:true},person:Field={name:'person_id',label:'Student / person',options:people,required:true},application:Field={name:'application_id',label:'Application (optional; must match student)',options:apps};
 const invoiceFields:Field[]=[{name:'description',label:'Charge description',required:true},amount,currency,{name:'due_on',type:'date'}];
 async function allocate(r:Row){try{const payments:Row[]=[];let offset=0;while(true){const page=await api<Row>(`finance/?kind=payments&status=VERIFIED&offset=${offset}`);const batch=rows(page,'results');payments.push(...batch);offset+=batch.length;if(!batch.length||offset>=Number(page.count))break;}const options=payments.filter(p=>p.person_id===r.person_id&&p.currency===r.currency&&(!r.application_id||p.application_id===r.application_id)).map(p=>({id:text(p,'id'),name:`${p.ref} · ${p.amount} ${p.currency} · Allocated ${p.allocated}`}));edit('Allocate verified payment','allocate',[{name:'payment_id',label:'Matching verified payment',options,required:true},amount,reason],{invoice_id:r.id});}catch(e){setError(message(e));}}
 return <section className="finance-workspace"><div className="tabs">{sections.map(s=><button key={s} className={section===s?'active':''} onClick={()=>{setSection(s);setSelected(null);setForm(null);setOffset(0);setSearch('');setStatus('');}}>{s==='rules'?'Commission rules':label(s)}</button>)}</div>{error&&<p className="error" role="alert">{error}</p>}{form&&<><button className="text-button" onClick={()=>setForm(null)}>Close finance form</button><ActionForm key={form.title+String(form.extra.id||'')} path="finance/" {...form} done={()=>void done()}/></>}
 {section==='overview'?<><p>Amounts remain separated by currency. No exchange-rate conversion is assumed.</p><div className="record-grid">{rows(data,'summary').map(r=><article className="card record-card" key={text(r,'currency')}><h2>{text(r,'currency')}</h2>{[['verified_payments','Verified student payments'],['invoice_outstanding','Outstanding invoices'],['verified_expenses','Verified operating expenses'],['expected_commissions','Expected institution commissions'],['received_commissions','Received institution commissions']].map(([key,title])=><p key={key}>{title}: <strong>{text(r,key)||'0.00'}</strong></p>)}</article>)}</div>{!rows(data,'summary').length&&<p>No financial transactions recorded.</p>}</>:<>
 <div className="toolbar">{editable&&section==='invoices'&&<button className="primary" disabled={locked} onClick={()=>edit('Create student invoice','invoice_create',[person,application,...invoiceFields])}>Create invoice</button>}{editable&&section==='payments'&&<button className="primary" disabled={locked} onClick={()=>edit('Record student payment','payment_create',[person,application,amount,currency,{name:'paid_on',type:'date',required:true},{name:'purpose',options:choices(['FEE','DEPOSIT','OTHER']),value:'FEE',required:true},{name:'method',options:choices(['CASH','BANK_TRANSFER','CARD','ONLINE','OTHER']),required:true},{name:'reference',label:'Transaction reference'}])}>Record payment</button>}{editable&&section==='expenses'&&<button className="primary" disabled={locked} onClick={()=>edit('Record operating expense','expense_create',[{name:'branch_id',options:rows(data,'branches').map(b=>({id:text(b,'id'),name:text(b,'name')})),required:true},{name:'category',required:true},{name:'payee',required:true},{name:'description',type:'textarea'},amount,currency,{name:'incurred_on',type:'date',required:true}])}>Record expense</button>}{data.can_manage_rules===true&&section==='rules'&&<button className="primary" disabled={locked} onClick={()=>edit('Create institution commission rule','rule_create',[{name:'institution_id',options:institutions,required:true},{name:'name',required:true},{name:'method',options:choices(['FIXED','PERCENTAGE']),required:true},{name:'value',type:'number',required:true,label:'Fixed amount / percentage'},currency])}>Create commission rule</button>}{editable&&section==='commissions'&&<button className="primary" disabled={locked} onClick={()=>edit('Record institution commission','commission_create',[{...application,required:true,label:'Application'},{name:'rule_id',options:rules,required:true,label:'Institution commission rule'},{name:'base_amount',type:'number',required:true,label:'Tuition / calculation base'},currency,{name:'due_on',type:'date'},reason])}>Record commission</button>}<a className="secondary" href={`/api/v1/finance/export/${kind}/?${new URLSearchParams({search,status})}`}>Export CSV</a></div>
 <div className="toolbar"><label>Search finance records<input value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}} placeholder="Reference, student or institution"/></label>{['invoices','payments','expenses','commissions'].includes(section)&&<label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);}}><option value="">All statuses</option>{(section==='invoices'?['DRAFT','ISSUED','CANCELLED']:section==='payments'?['PENDING','RECEIVED','VERIFIED','REFUNDED','CANCELLED']:section==='expenses'?['PENDING','VERIFIED','CANCELLED','VOIDED']:['PENDING','PARTIAL','RECEIVED','CANCELLED']).map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label>}</div>
 {selected?<article className="card record-card"><button className="text-button" onClick={()=>setSelected(null)}>← All {section}</button><h2>{kind==='payments'?text(selected,'ref'):text(selected,'reference')||text(selected,'name')}</h2><p>{text(selected,'person_name')||text(selected,'payee')||text(selected,'institution_name')||text(selected,'institution')}</p><p>{text(selected,'description')} · {text(selected,'currency')} {text(selected,'amount')||text(selected,'expected_amount')||text(selected,'value')} · {label(text(selected,'status')||text(selected,'method'))}</p>{section==='invoices'&&<><p>Paid: {text(selected,'paid')} · Balance: {text(selected,'balance')}</p><a className="secondary" href={`/api/v1/finance/invoices/${selected.id}/pdf/`}>Download invoice PDF</a></>}{section==='receipts'&&<><p>Payment status: {label(text(selected,'current_payment_status'))}</p><a className="secondary" href={`/api/v1/finance/receipts/${selected.id}/pdf/`}>Download receipt PDF</a></>}
 {['payments','expenses','commission_receipts'].includes(section)&&<>{rows(selected,'files').map(f=><p key={text(f,'id')}><a href={`/api/v1/finance/files/${f.id}/`}>{text(f,'filename')}</a></p>)}{editable&&(section==='payments'?['PENDING','RECEIVED'].includes(text(selected,'status')):section==='expenses'?selected.status==='PENDING':true)&&<form className="inline-form" onSubmit={e=>void upload(e)}><label>Upload proof (PDF, PNG, JPEG)<input name="file" type="file" accept="application/pdf,image/png,image/jpeg" required/></label><button className="primary" disabled={busy}>Upload proof</button></form>}</>}
 {section==='commissions'&&<><p>Commission rule: {text(selected.rule_snapshot as Row,'name')} · Version {text(selected.rule_snapshot as Row,'version')} · {label(text(selected.rule_snapshot as Row,'method'))} {text(selected.rule_snapshot as Row,'value')} · {text(selected.rule_snapshot as Row,'currency')}</p><p>Calculation base: {text(selected,'base_amount')} {text(selected,'currency')}</p><p>Received: {text(selected,'received')} · Outstanding: {text(selected,'balance')}</p>{rows(selected,'receipts').map(r=><div className="record-card" key={text(r,'id')}><strong>{text(r,'reference')}</strong><p>{text(r,'received_on')} · {text(r,'amount')} {text(selected,'currency')} · {text(r,'transaction_reference')}</p>{rows(r,'files').map(f=><p key={text(f,'id')}><a href={`/api/v1/finance/files/${f.id}/`}>{text(f,'filename')}</a></p>)}</div>)}</>}
 <h3>Financial history</h3>{history.map(e=><p key={text(e,'id')}>{date(text(e,'created_at'))} · {label(text(e,'action'))} · {text(e,'reason')}</p>)}</article>:<div className="record-grid">{rows(data,'results').map(r=><article className="card record-card" key={text(r,'id')}><h3>{kind==='payments'?text(r,'ref'):text(r,'reference')||text(r,'name')}</h3><p>{text(r,'person_name')||text(r,'payee')||text(r,'institution_name')||text(r,'institution')}</p><p>{text(r,'currency')} {text(r,'amount')||text(r,'expected_amount')||text(r,'value')} · {label(text(r,'status')||text(r,'method'))}</p>{section==='rules'&&<p>Version {text(r,'version')} · {label(text(r,'method'))}</p>}{section==='invoices'&&<p>Paid {text(r,'paid')} · Balance {text(r,'balance')} · {label(text(r,'settlement'))}</p>}{section==='commissions'&&<p>Received {text(r,'received')} · Balance {text(r,'balance')}</p>}
 <div className="toolbar"><button className="secondary" disabled={locked} onClick={()=>void open(r)}>View details</button>{section==='invoices'&&<a className="secondary" href={`/api/v1/finance/invoices/${r.id}/pdf/`}>Invoice PDF</a>}{section==='receipts'&&<a className="secondary" href={`/api/v1/finance/receipts/${r.id}/pdf/`}>Receipt PDF</a>}{section==='payments'&&!!r.receipt_id&&<a className="secondary" href={`/api/v1/finance/receipts/${r.receipt_id}/pdf/`}>Receipt PDF</a>}
 {editable&&section==='invoices'&&<>{r.status==='DRAFT'&&<><button className="secondary" disabled={locked} onClick={()=>edit('Edit draft invoice','invoice_edit',[...invoiceFields.map(f=>({...f,value:r[f.name]})),reason],{id:r.id})}>Edit draft</button><button className="primary" disabled={locked} onClick={()=>edit('Issue invoice','invoice_status',[reason],{id:r.id,status:'ISSUED'})}>Issue invoice</button></>}{r.status==='ISSUED'&&<button className="secondary" disabled={locked} onClick={()=>void allocate(r)}>Allocate payment</button>}{r.status!=='CANCELLED'&&<button className="secondary" disabled={locked} onClick={()=>edit('Cancel invoice','invoice_status',[reason],{id:r.id,status:'CANCELLED'})}>Cancel invoice</button>}</>}
 {editable&&section==='payments'&&!['REFUNDED','CANCELLED'].includes(text(r,'status'))&&<button className="secondary" disabled={locked} onClick={()=>edit('Review payment','payment_status',[{name:'status',options:choices(r.status==='PENDING'?['RECEIVED','CANCELLED']:r.status==='RECEIVED'?['VERIFIED','CANCELLED']:['REFUNDED']),required:true},reason],{id:r.id})}>Update payment</button>}
 {editable&&section==='expenses'&&['PENDING','VERIFIED'].includes(text(r,'status'))&&<button className="secondary" disabled={locked} onClick={()=>edit('Review operating expense','expense_status',[{name:'status',options:choices(r.status==='PENDING'?['VERIFIED','CANCELLED']:['VOIDED']),required:true},reason],{id:r.id})}>Review expense</button>}
 {editable&&section==='commissions'&&!['RECEIVED','CANCELLED'].includes(text(r,'status'))&&<><button className="primary" disabled={locked} onClick={()=>edit('Record institution commission receipt','commission_receive',[amount,{name:'received_on',type:'date',required:true},{name:'transaction_reference',required:true},reason],{id:r.id})}>Record received commission</button>{r.status==='PENDING'&&<button className="secondary" disabled={locked} onClick={()=>edit('Cancel unreceived commission','commission_cancel',[reason],{id:r.id})}>Cancel commission</button>}</>}
 {data.can_manage_rules===true&&section==='rules'&&<button className="secondary" disabled={locked} onClick={()=>edit('Create revised commission rule','rule_create',[{name:'name',value:r.name,required:true},{name:'method',options:choices(['FIXED','PERCENTAGE']),value:r.method,required:true},{name:'value',type:'number',value:r.value,required:true},{...currency,value:r.currency}],{institution_id:r.institution_id})}>Create new version</button>}
 </div></article>)}</div>}
 {!selected&&<div className="card-footer"><span>{text(data,'count')} records</span><button disabled={!offset||locked} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><button disabled={offset+50>=Number(data.count)||locked} onClick={()=>setOffset(offset+50)}>Next</button></div>}
 </>}
 </section>;
}
