'use client';
import {useEffect,useState} from 'react';
import {api,label,message,date,type Detail,type User} from '@/lib/api';
import {ActionForm,choices,reason} from './action-form';
type Priority={score:number;health:string;reasons:{kind:string;id:string;title:string;at?:string;weight:number}[]};
type Evidence={text_assistance_configured:boolean;generations:{id:string;result:{summary:string;draft:string;citations:string[];notice:string};at:string}[];engine:string;generated_at:string;summary:string;review_notice:string;priority:Priority;documents:{id:string;title:string;status:string;complete:boolean;required:boolean;evidence:string}[];timeline:{id:string;kind:string;title:string;at:string}[];course_matches:{offering_id:number;course:string;university:string;country:string;fee:string;currency:string;result:string;reasons:string[];missing_information:string[];mismatches:string[]}[];course_count:number;course_limit:number;draft:string;reviews:{id:string;kind:string;decision:string;note:string;reviewer:string;at:string}[]};
export function PersonInsights({detail,user}:{detail:Detail;user:User}){
 const [data,setData]=useState<Evidence|null>(null),[error,setError]=useState(''),[copied,setCopied]=useState(false);const path=`insights/people/${detail.person.id}/`;
 async function load(){try{setData(await api<Evidence>(path));setError('');}catch(e){setError(message(e));}}
 useEffect(()=>{void load();},[path]);
 return <details className="record-card"><summary>Evidence and assistance</summary>{error&&<p className="error" role="alert">{error}</p>}{data&&<><p>{data.summary}</p><p>{label(data.priority.health)} · Priority {data.priority.score}/100</p><p>{data.review_notice}</p><small>{data.engine} · {date(data.generated_at)}</small><button className="secondary" onClick={()=>void load()}>Refresh evidence</button>
 <h3>Attention reasons</h3><ul>{data.priority.reasons.map((r,i)=><li key={i}>{r.title} · {label(r.kind)} · Weight {r.weight}{r.at&&` · ${date(r.at)}`}<small> · Record {r.id}</small></li>)}</ul>
 <h3>Document completeness</h3>{data.documents.map(d=><p key={d.id}>{d.complete?'✓':'○'} {d.title} · {label(d.status)} · {d.required?'Required':'Optional'}<small> · {d.evidence}</small></p>)}
 <h3>Course matching assistance</h3><p>{data.course_count} available offerings; evaluating up to {data.course_limit}. Missing evidence requires counselor review.</p>{data.course_matches.slice(0,30).map(c=><article className="portal-item" key={c.offering_id}><strong>{c.course} · {c.university}</strong><p>{c.country} · {c.currency} {c.fee} · {label(c.result)}</p><ul>{[...c.reasons,...c.missing_information,...c.mismatches].map((r,i)=><li key={i}>{r}</li>)}</ul><small>Offering {c.offering_id}</small></article>)}
 <h3>Recent timeline summary</h3>{data.timeline.map((t,i)=><p key={`${t.kind}-${t.id}-${i}`}>{t.title} · {date(t.at)}<small> · {t.kind} {t.id}</small></p>)}
 <h3>Routine communication draft</h3><p className="portal-body">{data.draft}</p><button className="secondary" onClick={()=>void navigator.clipboard.writeText(data.draft).then(()=>setCopied(true)).catch(e=>setError(message(e)))}>{copied?'Copied':'Copy draft'}</button><p>Review and edit before sending through the communications composer.</p>
 {['ADMIN','MANAGER','COUNSELOR'].includes(user.role)&&<ActionForm title="Record your review" path={path} fields={[{name:'kind',required:true,options:choices(['SUMMARY','MATCHING','DOCUMENTS','PRIORITY','TIMELINE','DRAFT'])},{name:'decision',required:true,options:choices(['ACCEPTED','DISMISSED'])},{name:'generation_id',label:'Provider wording reviewed (optional)',options:data.generations.map(g=>({id:g.id,name:date(g.at)}))},reason]} done={()=>void load()}/>}<h3>Optional text assistance</h3><p>Local evidence tools work without an external service. External wording is available only when the operator configures a provider and request limit; it receives status evidence without names, contacts, files or private notes.</p>{data.text_assistance_configured&&['ADMIN','MANAGER','COUNSELOR'].includes(user.role)&&<ActionForm title="Request evidence-based wording" path={`${path}generate/`} fields={[reason]} done={()=>void load()}/>} {data.generations.map(g=><article className="portal-item" key={g.id}><p>{g.result.summary}</p><p className="portal-body">{g.result.draft}</p><small>Sources: {g.result.citations.join(', ')} · {date(g.at)}</small><p>{g.result.notice}</p></article>)}<h3>Review history</h3>{data.reviews.map(r=><p key={r.id}>{label(r.kind)} · {label(r.decision)} · {r.reviewer} · {date(r.at)}<br/>{r.note}</p>)}</>}</details>;
}
type Workspace={count:number;offset:number;priorities:(Priority&{id:string;name:string;ref:string})[];anomalies:{rule:string;count:number;examples:Record<string,unknown>[]}[];pipeline:{stage:string;lead_status:string;count:number}[];application_states:{state:string;count:number}[];overdue_followups:number;open_deadlines:number;scope_notice:string};
export function Insights({open}:{open:(id:string)=>Promise<void>}){
 const [data,setData]=useState<Workspace|null>(null),[error,setError]=useState(''),[offset,setOffset]=useState(0);
 useEffect(()=>{void api<Workspace>(`insights/workspace/?offset=${offset}`).then(setData).catch(e=>setError(message(e)));},[offset]);
 return <section className="card"><h2>Journey insights</h2>{error&&<p className="error" role="alert">{error}</p>}{data&&<><p>{data.count} active records · {data.overdue_followups} overdue follow-ups · {data.open_deadlines} open deadlines</p><p>{data.scope_notice}</p><h3>Follow-up priorities</h3>{data.priorities.map(p=><article className="portal-item" key={p.id}><button className="text-button" onClick={()=>void open(p.id)}>{p.name} · {p.ref}</button><p>{label(p.health)} · {p.score}/100</p><ul>{p.reasons.map((r,i)=><li key={i}>{r.title} · Weight {r.weight}</li>)}</ul></article>)}<div className="pagination"><button disabled={!offset} onClick={()=>setOffset(x=>Math.max(0,x-30))}>Previous</button><button disabled={offset+30>=data.count} onClick={()=>setOffset(x=>x+30)}>Next</button></div><h3>Anomaly checks</h3>{data.anomalies.map(a=><article className="portal-item" key={a.rule}><strong>{a.rule} · {a.count}</strong>{a.examples.map((e,i)=><p key={i}>{String(e.ref||e.person__ref||'')} · {String(e.full_name||e.title||'')}</p>)}</article>)}<h3>Pipeline</h3>{data.pipeline.map(p=><p key={`${p.stage}-${p.lead_status}`}>{label(p.stage)} · {label(p.lead_status)}: {p.count}</p>)}<h3>Application states</h3>{data.application_states.map(s=><p key={s.state}>{label(s.state)}: {s.count}</p>)}</>}</section>;
}
