'use client';
import {Pencil,CalendarClock,ChevronDown} from 'lucide-react';
import {CounselingRecord} from './counseling-record';
import {Admissions} from './admissions';
import {useState,useEffect,useRef} from 'react';
import {createPortal} from 'react-dom';
import {date,type Detail,type Masters,type User,type Row} from '@/lib/api';
import {ActionForm,choices,reason,type Field} from './action-form';
export function PersonTools({detail,user,masters,saved}:{detail:Detail;user:User;masters:Masters;saved:(m:string)=>Promise<void>}){
 const [form,setForm]=useState<{title:string;path:string;fields:Field[];method?:string;extra?:Row}|null>(null),[section,setSection]=useState('counseling');const p=detail.person,base=`people/${p.id}/`,permissions=user.permissions||{},editable=permissions.edit&&permissions.edit!=='documents',work=!!permissions.work;
 const edit=(title:string,path:string,fields:Field[],method='POST',extra?:Row)=>setForm({title,path,fields,method,extra});
 const [correctionTab,setCorrectionTab]=useState<'followups'|'activities'>('followups');
 const openFollowups=detail.followups.filter(f=>!f.completed_at&&!['CANCELLED'].includes(f.status||'')),correctableActivities=detail.activities.filter(a=>typeof a.id==='number');
 const dialog=useRef<HTMLElement>(null);
 useEffect(()=>{if(!form)return;const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';const controls=()=>Array.from(dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')||[]).filter(el=>el.getClientRects().length>0);dialog.current?.querySelector<HTMLElement>('input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')?.focus();const keydown=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();setForm(null);}if(e.key==='Tab'){const items=controls(),first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',keydown);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',keydown);previous?.focus();};},[form]);
 const profileFields:Field[]=['full_name','dob','address','guardian_name','guardian_contact','preferred_country','preferred_course','preferred_intake','preferred_university','highest_education','work_experience','previous_visa_refusal','best_contact_method'].map(name=>({name,required:name==='full_name',value:p[name],type:name==='dob'?'date':name==='work_experience'?'textarea':'text',options:name==='previous_visa_refusal'?choices(['YES','NO','UNKNOWN']):name==='best_contact_method'?choices(['CALL','WHATSAPP','EMAIL','MEETING']):undefined}));
 return <section className="person-tools"><div className="toolbar">{editable&&<button className="secondary" onClick={()=>edit('Edit profile',base+'profile/',profileFields,'PATCH')}>Edit profile</button>}{permissions.convert&&<button className="secondary" onClick={()=>edit('Update lifecycle',base+'lifecycle/',[...(p.stage==='STUDENT'?[{name:'student_state',options:choices(['ACTIVE','ENROLLED','DEFERRED','WITHDRAWN','ARCHIVED']),value:p.student_state}]:[{name:'status',options:choices(['NEW','CONTACTED','COUNSELING','INTERESTED','DOCUMENT_COLLECTION','APPLICATION_READY','LOST','ON_HOLD']),value:p.lead_status},{name:'lost_reason_id',type:'number',options:masters.lost_reasons},{name:'hold_until',type:'datetime-local'}]),{name:'temperature',options:choices(['HOT','WARM','COLD']),value:p.temperature},{...reason,required:false,help:'Required for backward/skipped stages, Lost reasons needing notes, and reactivation.'}])}>Lifecycle / priority</button>}{permissions.reassign&&<><button className="secondary" onClick={()=>edit('Assign visitor to counselor',base+'reassign/',[{name:'owner_id',type:'number',options:masters.owners.filter(o=>o.branch_id===p.branch),required:true,value:p.owner},...(p.owner?[reason]:[])])}>Assign counselor</button><button className="secondary" onClick={()=>edit('Assign case team',base+'team/',[{name:'user_id',type:'number',options:masters.users,required:true},{name:'role_on_case',options:choices(['DOCUMENTATION','VISA','OTHER']),value:'DOCUMENTATION'},{name:'active',type:'checkbox',value:true},reason])}>Case team</button></>}{permissions.convert&&(p.stage==='STUDENT'||p.lead_status==='CONVERTED')&&<button className="secondary" onClick={()=>edit('Revert student to lead',base+'lifecycle/',[reason],'POST',{revert_to_lead:true})}>Undo conversion / revert to lead</button>}{permissions.archive&&<button className="secondary" onClick={()=>edit('Archive person',base+'archive/',[reason])}>Archive</button>}{work&&<button className="secondary" onClick={()=>edit('Add person task','tasks/',[{name:'title',required:true},{name:'priority',options:choices(['LOW','NORMAL','HIGH','URGENT']),value:'NORMAL'},{name:'due_at',type:'datetime-local',required:true}], 'POST',{person_id:p.id,owner_id:user.id})}>Add task</button>}</div>
 {form&&createPortal(<div className="modal-overlay"><section ref={dialog} className="modal profile-edit-modal" role="dialog" aria-modal="true" aria-label={form.title}><div className="modal-header"><h2>{form.title}</h2><button className="secondary" onClick={()=>setForm(null)} aria-label="Close edit form">Close</button></div><ActionForm key={form.title+form.path} {...form} done={()=>{setForm(null);void saved('Record updated.');}}/></section></div>,document.body)}
 <div className="tabs">{['counseling','profile','contacts','education','tasks','sla','admissions'].map(s=><button key={s} className={section===s?'active':''} onClick={()=>setSection(s)}>{s==='sla'?'Service levels':s[0].toUpperCase()+s.slice(1)}</button>)}</div>
 {section==='counseling'&&<CounselingRecord detail={detail} user={user} masters={masters} saved={saved}/>}
 {section==='admissions'&&<Admissions personId={p.id} user={user} masters={masters}/>}
 {section==='profile'&&<><dl className="data-fields">{['dob','lost_reason_name','hold_until','address','guardian_name','guardian_contact','highest_education','preferred_intake','preferred_university','previous_visa_refusal','work_experience','source_file','import_row_number'].map(k=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(p[k]||'—')}</dd></div>)}</dl>{editable&&<button className="secondary" onClick={()=>edit('Update source and tags',base+'profile/',[{name:'source',type:'number',options:masters.sources,value:p.source},{name:'campaign',type:'number',options:masters.campaigns,value:p.campaign},{name:'source_detail',type:'number',options:masters.source_details,value:p.source_detail},{name:'tags',type:'multiselect',options:masters.tags,value:p.tags,help:'Select all applicable tags.'}],'PATCH')}>Source / campaign / tags</button>}</>}
 {section==='contacts'&&<>{editable&&<button className="secondary" onClick={()=>edit('Add contact',base+'contacts/',[{name:'type',options:choices(['PHONE','EMAIL','WHATSAPP','MESSENGER']),value:'PHONE'},{name:'raw_value',label:'Contact value',required:true},{name:'is_primary',type:'checkbox',value:false},{name:'is_shared',type:'checkbox',value:false},{name:'shared_with_note',label:'Shared contact context'}, {...reason,required:false}])}>Add contact</button>}{(detail.contacts||[]).map(c=><div className="record-card" key={String(c.id)}><strong>{String(c.type)} · {String(c.raw_value)}</strong><p>{c.verified_at?'Verified via '+c.verified_via:'Unverified'} {c.is_primary?' · Primary':''} {c.is_shared?' · Shared: '+c.shared_with_note:''}</p>{editable&&<button className="secondary" onClick={()=>edit('Edit contact',base+`contacts/${c.id}/`,[{name:'type',options:choices(['PHONE','EMAIL','WHATSAPP','MESSENGER']),value:c.type},{name:'raw_value',required:true,value:c.raw_value},{name:'is_primary',type:'checkbox',value:c.is_primary},{name:'is_shared',type:'checkbox',value:c.is_shared},{name:'shared_with_note',value:c.shared_with_note},{...reason,required:false}],'PATCH')}>Edit</button>}</div>)}</>}
 {section==='education'&&<>{permissions.edit&&<div className="toolbar"><button className="secondary" onClick={()=>edit('Add education',base+'education/',[{name:'level',required:true},{name:'institute',required:true},{name:'degree_stream'},{name:'grade_or_percent'},{name:'passed_year',type:'number'}])}>Add education</button><button className="secondary" onClick={()=>edit('Add test score',base+'test-scores/',[{name:'test',options:choices(['IELTS','PTE','TOEFL','DUOLINGO','SAT','GRE','GMAT','OTHER']),required:true},{name:'status',options:choices(['TAKEN','PLANNED','NOT_TAKEN']),value:'PLANNED'},{name:'score'},{name:'test_date',type:'date'}])}>Add test score</button></div>}{[...(detail.education||[]),...(detail.test_scores||[])].map((r,i)=><div className="record-card" key={i}>{Object.entries(r).filter(([k])=>!['id','person_id'].includes(k)).map(([k,v])=><p key={k}>{k.replaceAll('_',' ')}: {String(v??'—')}</p>)}{permissions.edit&&<button className="secondary" onClick={()=>edit(r.test?'Edit test score':'Edit education',base+(r.test?`test-scores/${r.id}/`:`education/${r.id}/`),Object.keys(r).filter(k=>!['id','person_id'].includes(k)).map(name=>({name,value:r[name],type:name==='passed_year'?'number':name==='test_date'?'date':'text',options:name==='test'?choices(['IELTS','PTE','TOEFL','DUOLINGO','SAT','GRE','GMAT','OTHER']):name==='status'?choices(['TAKEN','PLANNED','NOT_TAKEN']):undefined})),'PATCH')}>Edit</button>}</div>)}</>}
 {section==='tasks'&&(detail.tasks||[]).map(t=><div className="record-card" key={String(t.id)}><h3>{String(t.title)}</h3><p>{String(t.owner_name)} · {String(t.status)} · {date(String(t.due_at))}</p>{work&&<button className="secondary" onClick={()=>edit('Update task',`tasks/${t.id}/update/`,[{name:'status',options:choices(['OPEN','IN_PROGRESS','COMPLETED','CANCELLED']),value:t.status},{name:'due_at',type:'datetime-local'}])}>Update</button>}</div>)}
 {section==='sla'&&(detail.sla_timers||[]).map(t=><div className="record-card" key={String(t.id)}><strong>{String(t.rule__name)}</strong><p>{date(String(t.due_at))} · {t.satisfied_at?'Met':t.breached_at?'Breached':'Open'}</p></div>)}
 {work&&<details className="record-maintenance"><summary><Pencil size={18}/><span><strong>Corrections and schedule changes</strong><small>Fix an earlier entry or change an upcoming follow-up.</small></span><ChevronDown size={18}/></summary><div className="maintenance-body"><div className="maintenance-tabs" role="group" aria-label="Choose correction type"><button type="button" className={correctionTab==='followups'?'active':''} onClick={()=>setCorrectionTab('followups')}><CalendarClock size={16}/>Upcoming follow-ups <span>{openFollowups.length}</span></button><button type="button" className={correctionTab==='activities'?'active':''} onClick={()=>setCorrectionTab('activities')}><Pencil size={16}/>Activity corrections <span>{correctableActivities.length}</span></button></div><p className="maintenance-help">{correctionTab==='followups'?'Change the date, instructions or status of an open follow-up.':'Corrections are added to the history. The original entry is retained.'}</p><div className="maintenance-list">{correctionTab==='followups'?openFollowups.map(f=><article className="maintenance-row" key={f.id}><div><h4>{f.subject}</h4><small>{date(f.due_at)} · {f.owner_name||'Unassigned'}</small>{f.notes&&<p>{f.notes}</p>}</div><button className="secondary" type="button" onClick={()=>edit('Change follow-up',`followups/${f.id}/update/`,[{name:'due_at',label:'Date and time (Nepal)',type:'datetime-local',value:f.due_at},{name:'status',options:choices(['OPEN','IN_PROGRESS','CANCELLED']),value:f.status||'OPEN'},{name:'notes',label:'Follow-up instructions',type:'textarea',value:f.notes||''}])}><CalendarClock size={15}/>Change schedule</button></article>):correctableActivities.map(a=><article className="maintenance-row" key={a.id}><div><h4>{a.subject}</h4><small>{a.actor} · {date(a.performed_at)}</small>{a.notes&&<p>{a.notes}</p>}</div><button className="secondary" type="button" onClick={()=>edit('Correct activity entry',base+`activities/${a.id}/correct/`,[{name:'subject',label:'Corrected subject',required:true,value:a.subject},{name:'notes',label:'Corrected notes',type:'textarea',value:a.notes},reason])}><Pencil size={15}/>Correct entry</button></article>)}{!(correctionTab==='followups'?openFollowups:correctableActivities).length&&<p className="maintenance-empty">{correctionTab==='followups'?'No upcoming follow-ups to change.':'No activity entries to correct.'}</p>}</div></div></details>}
 </section>;
}
