'use client';
import {Admissions} from './admissions';
import {useState} from 'react';
import {date,type Detail,type Masters,type User,type Row} from '@/lib/api';
import {ActionForm,choices,reason,type Field} from './action-form';
export function PersonTools({detail,user,masters,saved}:{detail:Detail;user:User;masters:Masters;saved:(m:string)=>Promise<void>}){
 const [form,setForm]=useState<{title:string;path:string;fields:Field[];method?:string;extra?:Row}|null>(null),[section,setSection]=useState('profile');const p=detail.person,base=`people/${p.id}/`,permissions=user.permissions||{},editable=permissions.edit&&permissions.edit!=='documents',work=!!permissions.work;
 const edit=(title:string,path:string,fields:Field[],method='POST',extra?:Row)=>setForm({title,path,fields,method,extra});
 const profileFields:Field[]=['full_name','dob','address','guardian_name','guardian_contact','preferred_country','preferred_course','preferred_intake','preferred_university','highest_education','work_experience','previous_visa_refusal','best_contact_method'].map(name=>({name,required:name==='full_name',value:p[name],type:name==='dob'?'date':name==='work_experience'?'textarea':'text',options:name==='previous_visa_refusal'?choices(['YES','NO','UNKNOWN']):name==='best_contact_method'?choices(['CALL','WHATSAPP','EMAIL','MEETING']):undefined}));
 return <section className="person-tools"><div className="toolbar">{editable&&<button className="secondary" onClick={()=>edit('Edit profile',base+'profile/',profileFields,'PATCH')}>Edit profile</button>}{permissions.convert&&<button className="secondary" onClick={()=>edit('Update lifecycle',base+'lifecycle/',[...(p.stage==='STUDENT'?[{name:'student_state',options:choices(['ACTIVE','ENROLLED','DEFERRED','WITHDRAWN','ARCHIVED']),value:p.student_state}]:[{name:'status',options:choices(['NEW','CONTACTED','COUNSELING','INTERESTED','DOCUMENT_COLLECTION','APPLICATION_READY','LOST','ON_HOLD']),value:p.lead_status},{name:'lost_reason_id',type:'number',options:masters.lost_reasons},{name:'hold_until',type:'datetime-local'}]),{name:'temperature',options:choices(['HOT','WARM','COLD']),value:p.temperature},{...reason,required:false,help:'Required for backward/skipped stages, Lost reasons needing notes, and reactivation.'}])}>Lifecycle / priority</button>}{permissions.reassign&&<><button className="secondary" onClick={()=>edit('Reassign owner',base+'reassign/',[{name:'owner_id',type:'number',options:masters.owners.filter(o=>o.branch_id===p.branch),required:true},reason])}>Reassign</button><button className="secondary" onClick={()=>edit('Assign case team',base+'team/',[{name:'user_id',type:'number',options:masters.users,required:true},{name:'role_on_case',options:choices(['DOCUMENTATION','VISA','OTHER']),value:'DOCUMENTATION'},{name:'active',type:'checkbox',value:true},reason])}>Case team</button></>}{permissions.reassign&&p.stage==='STUDENT'&&<button className="secondary" onClick={()=>edit('Revert student to lead',base+'lifecycle/',[reason],'POST',{revert_to_lead:true})}>Revert to lead</button>}{permissions.archive&&<button className="secondary" onClick={()=>edit('Archive person',base+'archive/',[reason])}>Archive</button>}{work&&<button className="secondary" onClick={()=>edit('Add person task','tasks/',[{name:'title',required:true},{name:'priority',options:choices(['LOW','NORMAL','HIGH','URGENT']),value:'NORMAL'},{name:'due_at',type:'datetime-local',required:true}], 'POST',{person_id:p.id,owner_id:user.id})}>Add task</button>}</div>
 {form&&<><button className="text-button" onClick={()=>setForm(null)}>Close form</button><ActionForm key={form.title+form.path} {...form} done={()=>{setForm(null);void saved('Record updated.');}}/></>}
 <div className="tabs">{['profile','contacts','education','tasks','sla','admissions'].map(s=><button key={s} className={section===s?'active':''} onClick={()=>setSection(s)}>{s==='sla'?'Service levels':s[0].toUpperCase()+s.slice(1)}</button>)}</div>
 {section==='admissions'&&<Admissions personId={p.id} user={user} masters={masters}/>}
 {section==='profile'&&<><dl className="data-fields">{['dob','lost_reason_name','hold_until','address','guardian_name','guardian_contact','highest_education','preferred_intake','preferred_university','previous_visa_refusal','work_experience','source_file','import_row_number'].map(k=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(p[k]||'—')}</dd></div>)}</dl>{editable&&<button className="secondary" onClick={()=>edit('Update source and tags',base+'profile/',[{name:'source',type:'number',options:masters.sources,value:p.source},{name:'campaign',type:'number',options:masters.campaigns,value:p.campaign},{name:'source_detail',type:'number',options:masters.source_details,value:p.source_detail},{name:'tags',type:'multiselect',options:masters.tags,value:p.tags,help:'Select all applicable tags.'}],'PATCH')}>Source / campaign / tags</button>}</>}
 {section==='contacts'&&<>{editable&&<button className="secondary" onClick={()=>edit('Add contact',base+'contacts/',[{name:'type',options:choices(['PHONE','EMAIL','WHATSAPP','MESSENGER']),value:'PHONE'},{name:'raw_value',label:'Contact value',required:true},{name:'is_primary',type:'checkbox',value:false},{name:'is_shared',type:'checkbox',value:false},{name:'shared_with_note',label:'Shared contact context'}, {...reason,required:false}])}>Add contact</button>}{(detail.contacts||[]).map(c=><div className="record-card" key={String(c.id)}><strong>{String(c.type)} · {String(c.raw_value)}</strong><p>{c.verified_at?'Verified via '+c.verified_via:'Unverified'} {c.is_primary?' · Primary':''} {c.is_shared?' · Shared: '+c.shared_with_note:''}</p>{editable&&<button className="secondary" onClick={()=>edit('Edit contact',base+`contacts/${c.id}/`,[{name:'type',options:choices(['PHONE','EMAIL','WHATSAPP','MESSENGER']),value:c.type},{name:'raw_value',required:true,value:c.raw_value},{name:'is_primary',type:'checkbox',value:c.is_primary},{name:'is_shared',type:'checkbox',value:c.is_shared},{name:'shared_with_note',value:c.shared_with_note},{...reason,required:false}],'PATCH')}>Edit</button>}</div>)}</>}
 {section==='education'&&<>{permissions.edit&&<div className="toolbar"><button className="secondary" onClick={()=>edit('Add education',base+'education/',[{name:'level',required:true},{name:'institute',required:true},{name:'degree_stream'},{name:'grade_or_percent'},{name:'passed_year',type:'number'}])}>Add education</button><button className="secondary" onClick={()=>edit('Add test score',base+'test-scores/',[{name:'test',options:choices(['IELTS','PTE','TOEFL','DUOLINGO','SAT','GRE','GMAT','OTHER']),required:true},{name:'status',options:choices(['TAKEN','PLANNED','NOT_TAKEN']),value:'PLANNED'},{name:'score'},{name:'test_date',type:'date'}])}>Add test score</button></div>}{[...(detail.education||[]),...(detail.test_scores||[])].map((r,i)=><div className="record-card" key={i}>{Object.entries(r).filter(([k])=>!['id','person_id'].includes(k)).map(([k,v])=><p key={k}>{k.replaceAll('_',' ')}: {String(v??'—')}</p>)}{permissions.edit&&<button className="secondary" onClick={()=>edit(r.test?'Edit test score':'Edit education',base+(r.test?`test-scores/${r.id}/`:`education/${r.id}/`),Object.keys(r).filter(k=>!['id','person_id'].includes(k)).map(name=>({name,value:r[name],type:name==='passed_year'?'number':name==='test_date'?'date':'text',options:name==='test'?choices(['IELTS','PTE','TOEFL','DUOLINGO','SAT','GRE','GMAT','OTHER']):name==='status'?choices(['TAKEN','PLANNED','NOT_TAKEN']):undefined})),'PATCH')}>Edit</button>}</div>)}</>}
 {section==='tasks'&&(detail.tasks||[]).map(t=><div className="record-card" key={String(t.id)}><h3>{String(t.title)}</h3><p>{String(t.owner_name)} · {String(t.status)} · {date(String(t.due_at))}</p>{work&&<button className="secondary" onClick={()=>edit('Update task',`tasks/${t.id}/update/`,[{name:'status',options:choices(['OPEN','IN_PROGRESS','COMPLETED','CANCELLED']),value:t.status},{name:'due_at',type:'datetime-local'}])}>Update</button>}</div>)}
 {section==='sla'&&(detail.sla_timers||[]).map(t=><div className="record-card" key={String(t.id)}><strong>{String(t.rule__name)}</strong><p>{date(String(t.due_at))} · {t.satisfied_at?'Met':t.breached_at?'Breached':'Open'}</p></div>)}
 {work&&<details><summary>Correct an activity / reschedule a follow-up</summary>{detail.activities.filter(a=>typeof a.id==='number').map(a=><div className="record-card" key={a.id}><strong>{a.subject}</strong><button className="text-button" onClick={()=>edit('Correct activity (original is retained)',base+`activities/${a.id}/correct/`,[{name:'subject',required:true,value:a.subject},{name:'notes',type:'textarea',value:a.notes},reason])}>Add correction</button></div>)}{detail.followups.filter(f=>!f.completed_at).map(f=><div className="record-card" key={f.id}><strong>{f.subject}</strong><button className="text-button" onClick={()=>edit('Reschedule / cancel follow-up',`followups/${f.id}/update/`,[{name:'due_at',type:'datetime-local'},{name:'status',options:choices(['OPEN','IN_PROGRESS','CANCELLED'])},{name:'notes',type:'textarea'}])}>Update follow-up</button></div>)}</details>}
 </section>;
}
