 'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Check} from 'lucide-react';
import {api,ApiError,message,type Row} from '@/lib/api';
const types=['Passport','Class 10th','Class 12th','Bachelor transcripts','Master transcripts','Academic Transcripts','Certificates','Citizenship / ID','English Test Score','CV / Resume','Financial Documents','Photographs','Recommendation Letters','Experience Letters','Medical / Police Report','Other'];
type Work=(work:()=>Promise<unknown>,success:string)=>Promise<boolean>;
function DocumentItem({doc,canUpload,busy,run}:{doc:Row;canUpload:boolean;busy:boolean;run:Work}){
 const unlabelled=doc.type==='Unclassified',initialType=unlabelled?'':types.includes(String(doc.type))?String(doc.type):'custom';
 const [editing,setEditing]=useState(unlabelled),[kind,setKind]=useState(initialType),[custom,setCustom]=useState(initialType==='custom'?String(doc.type):''),[title,setTitle]=useState(String(doc.title));
 function edit(){setKind(initialType);setCustom(initialType==='custom'?String(doc.type):'');setTitle(String(doc.title));setEditing(true);}
 async function save(){if(await run(()=>api(`admissions/documents/${doc.id}/`,'PATCH',{type:kind==='custom'?custom.trim():kind,title:title.trim()}),'Document details saved.'))setEditing(false);}
 return <tr><td>{canUpload&&editing?<><select aria-label={`Document type for ${doc.title}`} disabled={busy} value={kind} onChange={e=>setKind(e.target.value)}><option value="">Select type</option>{types.map(t=><option key={t} value={t}>{t}</option>)}<option value="custom">Write another type…</option></select>{kind==='custom'&&<input aria-label={`Custom type for ${doc.title}`} disabled={busy} maxLength={80} value={custom} onChange={e=>setCustom(e.target.value)} placeholder="Document type"/>}</>:unlabelled?'Not selected':String(doc.type)}</td><td>{canUpload&&editing?<input aria-label={`Document name for ${doc.title}`} disabled={busy} maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Document name"/>:<span>{String(doc.title)}</span>}</td><td><div className="document-line-actions">{canUpload&&editing?<><button className="primary" type="button" disabled={busy||!title.trim()||!kind||kind==='custom'&&!custom.trim()} onClick={()=>void save()}>Save</button>{!unlabelled&&<button className="secondary" type="button" disabled={busy} onClick={()=>setEditing(false)}>Cancel</button>}</>:canUpload&&<button className="secondary" type="button" disabled={busy} onClick={edit}>Edit</button>}{Number(doc.version)>0&&<a className="secondary" href={`/api/v1/admissions/documents/${doc.id}/versions/${doc.version}/?inline=1`} target="_blank" rel="noopener noreferrer">View</a>}{Number(doc.version)>0&&<a className="secondary" href={`/api/v1/admissions/documents/${doc.id}/versions/${doc.version}/`} target="_blank" rel="noopener noreferrer">Download</a>}{canUpload&&<button className="doc-delete" type="button" disabled={busy} onClick={()=>{if(window.confirm(`Delete "${doc.title}" from this profile?`))void run(()=>api(`admissions/documents/${doc.id}/`,'DELETE'),'Document deleted.');}}>Delete</button>}</div></td></tr>;
}
export function ProfileDocuments({personId,canUpload,saved}:{personId:string;canUpload:boolean;saved:(m:string)=>Promise<void>}){
 const [documents,setDocuments]=useState<Row[]>([]),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');const batchKey=useRef(''),input=useRef<HTMLInputElement>(null);
 async function load(){const r=await api<{results:Row[]}>(`admissions/documents/?person_id=${personId}`);setDocuments(r.results);}
 useEffect(()=>{setLoading(true);setFiles([]);batchKey.current='';void load().catch(e=>setError(message(e))).finally(()=>setLoading(false));},[personId]);
 const run:Work=async(work,success)=>{setBusy(true);setError('');setNotice('');try{await work();await load();setNotice(success);await saved(success);return true;}catch(e){const fields=e instanceof ApiError?e.data.fields as {files?:Record<string,string[]>}|undefined:undefined;setError(fields?.files?Object.entries(fields.files).map(([filename,reasons])=>`${filename}: ${reasons.join(' ')}`).join(' '):message(e));return false;}finally{setBusy(false);}};
 function choose(selected:File[]){batchKey.current='';setError('');if(selected.length>20){setFiles([]);setError('Choose up to 20 files at a time.');return;}setFiles(selected);}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!files.length)return;const fd=new FormData();fd.set('person_id',personId);files.forEach(f=>fd.append('files',f));if(!batchKey.current)batchKey.current=crypto.randomUUID();await run(async()=>{await api('admissions/documents/upload/','POST',fd,batchKey.current);batchKey.current='';setFiles([]);if(input.current)input.current.value='';},'Uploaded successfully. Choose the document type and save the details for each new file.');}
 return <section className="profile-documents"><div className="document-section-title"><h3>Documents</h3>{documents.some(d=>Number(d.version)>0)&&<a className="secondary" href={`/api/v1/admissions/documents/download-all/?person_id=${personId}`}>Download all documents</a>}</div>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="doc-success" role="status"><Check size={16}/>{notice}</p>}{canUpload&&<form className="document-upload-simple" onSubmit={e=>void upload(e)}><label>Upload files<input ref={input} type="file" accept="application/pdf,image/png,image/jpeg" multiple disabled={busy} onChange={e=>choose(Array.from(e.target.files||[]))}/></label><button className="primary" disabled={busy||!files.length}>{busy?'Please wait…':'Upload files'}</button></form>}<div className="document-lines"><table><thead><tr><th>Document type</th><th>Document</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan={3}>Loading documents…</td></tr>:documents.length?documents.map(doc=><DocumentItem key={String(doc.id)} doc={doc} canUpload={canUpload} busy={busy} run={run}/>):<tr><td colSpan={3}>No documents uploaded.</td></tr>}</tbody></table></div></section>;
}
