 'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {api,ApiError,date,label,message,type Row} from '@/lib/api';
const types=['Passport','Class 10th','Class 12th','Bachelor transcripts','Master transcripts','Academic Transcripts','Certificates','Citizenship / ID','English Test Score','CV / Resume','Financial Documents','Photographs','Recommendation Letters','Experience Letters','Medical / Police Report','Other'];
export function ProfileDocuments({personId,canUpload,saved}:{personId:string;canUpload:boolean;saved:(m:string)=>Promise<void>}){
 const [documents,setDocuments]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const batchKey=useRef('');
 async function load(){try{const r=await api<{results:Row[]}>(`admissions/documents/?person_id=${personId}`);setDocuments(r.results);}catch(e){setError(message(e));}}
 useEffect(()=>{void load();batchKey.current='';},[personId]);
 async function run(work:()=>Promise<unknown>,success:string){setBusy(true);setError('');setNotice('');try{await work();await load();setNotice(success);await saved(success);}catch(e){const fields=e instanceof ApiError?e.data.fields as {files?:Record<string,string[]>}|undefined:undefined;setError(fields?.files?Object.entries(fields.files).map(([filename,reasons])=>`${filename}: ${reasons.join(' ')}`).join(' '):message(e));}finally{setBusy(false);}}
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,fd=new FormData(form);fd.set('person_id',personId);if(!batchKey.current)batchKey.current=crypto.randomUUID();await run(async()=>{await api('admissions/documents/upload/','POST',fd,batchKey.current);batchKey.current='';form.reset();},'Files uploaded. Select a type and name for each file below.');}
 function metadata(e:FormEvent<HTMLFormElement>,doc:Row){e.preventDefault();const fd=new FormData(e.currentTarget);void run(()=>api(`admissions/documents/${doc.id}/`,'PATCH',{type:fd.get('type'),title:fd.get('title')}),'Document details saved.');}
 return <section className="profile-documents"><h3>Uploaded documents (optional)</h3><p>Upload scanned files or files received on WhatsApp, then label each file. The counselor can see and download the files from this profile.</p>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{canUpload&&<form onSubmit={e=>void upload(e)}><label>Choose files (up to 20 at once; PDF, PNG or JPEG)<input type="file" name="files" accept="application/pdf,image/png,image/jpeg" multiple required disabled={busy} onChange={()=>{batchKey.current='';}}/></label><button className="primary" disabled={busy}>{busy?'Please wait…':'Upload selected files'}</button></form>}{!documents.length&&<p>No documents uploaded yet.</p>}{documents.map(doc=><article className="document-file-card" key={String(doc.id)}><h4>{String(doc.title)}</h4><p>{String(doc.type)} · {label(String(doc.status))}</p>{Number(doc.version)>0&&<a className="secondary" href={`/api/v1/admissions/documents/${doc.id}/versions/${doc.version}/`} target="_blank" rel="noopener noreferrer">Open / download file</a>}{Boolean(doc.verified_at)&&<p>Verified {date(String(doc.verified_at))}</p>}{canUpload&&<form key={`${doc.id}-${doc.type}-${doc.title}`} onSubmit={e=>metadata(e,doc)}><div className="form-grid"><label>Document type<input name="type" list={`document-types-${doc.id}`} required maxLength={80} defaultValue={doc.type==='Unclassified'?'':String(doc.type)} placeholder="Select or write, e.g. Class 10th"/><datalist id={`document-types-${doc.id}`}>{types.map(t=><option value={t} key={t}/>)}</datalist></label><label>Document name<input name="title" required maxLength={160} defaultValue={String(doc.title)}/></label></div><button className="secondary" disabled={busy}>Save type and name</button></form>}</article>)}</section>;
}
