'use client';
import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {api,date,label,message,type Row,type User} from '@/lib/api';
import {ActionForm,choices,reason,type Field} from './action-form';

const text=(r:Row,k:string)=>String(r[k]??''),rows=(r:Row,k:string)=>(r[k]||[]) as Row[];
type Form={title:string;fields:Field[];extra?:Row};
const visaStates=['PREPARING','READY','SUBMITTED','BIOMETRICS_PENDING','INTERVIEW','ADMIN_PROCESSING','APPROVED','REFUSED','WITHDRAWN'];

export function Progression({application,user,changed}:{application:Row;user:User;changed:()=>Promise<void>}){
 const [data,setData]=useState<Row|null>(null),[workflows,setWorkflows]=useState<Row[]>([]),[form,setForm]=useState<Form|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0),[saving,setSaving]=useState(false);
 const path=`progression/applications/${application.id}/`;
 const refresh=useCallback(async()=>{try{const [journey,w]=await Promise.all([api<Row>(path),api<Row>('progression/workflows/')]);setData(journey);setWorkflows(rows(w,'results'));setError('');}catch(e){setError(message(e));}},[path]);
 useEffect(()=>{void refresh();},[refresh]);
 const edit=(title:string,action:string,fields:Field[],extra?:Row)=>setForm({title,fields,extra:{action,...extra}});
 async function done(){setSaving(true);try{setForm(null);setRevision(r=>r+1);await refresh();await changed();}finally{setSaving(false);}}
 const documents=rows(application,'documents').map(d=>({id:text(d,'id'),name:`${d.title} · ${label(text(d,'status'))}`}));
 if(!data)return <section className="record-card"><h3>Offer, visa and enrollment</h3><p>{error||'Loading journey…'}</p></section>;
 const editable=data.can_edit===true,locked=!!form||saving,deposit=data.deposit as Row|null;
 return <section className="journey-panel"><h2>Offer, visa and enrollment</h2>{error&&<p className="error" role="alert">{error}</p>}{form&&<><button className="text-button" onClick={()=>setForm(null)}>Close journey form</button><ActionForm key={form.title+String(form.extra?.id||form.extra?.case_id||'')} path={path} {...form} done={()=>void done()}/></>}
  <h3>Offer conditions and acceptance</h3>{rows(data,'conditions').map(c=><div className="record-card" key={text(c,'id')}><strong>{text(c,'title')}</strong><p>{label(text(c,'status'))}</p>{editable&&<button className="secondary" disabled={locked} onClick={()=>edit('Review offer condition','condition',[{name:'status',options:choices(['PENDING','MET','WAIVED']),value:c.status,required:true},{name:'document_id',label:'Supporting document (optional)',options:documents},reason],{id:c.id})}>Review condition</button>}</div>)}
  {rows(data,'offers').map(o=><div className="record-card" key={text(o,'id')}><strong>{label(text(o,'type'))} · {text(o,'reference')||'Institution offer'}</strong><p>{label(text(o,'status'))}{o.expires_at?` · Expires ${date(text(o,'expires_at'))}`:''}</p>{editable&&o.status==='RECEIVED'&&data.state==='OFFER_RECEIVED'&&<button className="primary" disabled={locked} onClick={()=>edit('Confirm offer acceptance','accept_offer',[reason],{offer_id:o.id})}>Accept offer</button>}</div>)}
  <h3>Institution deposit and basic payments</h3>{deposit?<p>Required: {text(deposit,'currency')} {text(deposit,'amount')} · Verified: {text(data,'verified_deposit_total')} {deposit.waived?'· Waived':''} {deposit.due_at?`· Due ${date(text(deposit,'due_at'))}`:''}</p>:<p>No institution deposit requirement recorded.</p>}
  {editable&&<div className="toolbar"><button className="secondary" disabled={locked} onClick={()=>edit('Institution deposit requirement','deposit',[{name:'amount',type:'number',required:true,value:deposit?.amount},{name:'currency',required:true,value:deposit?.currency||application.currency||'USD'},{name:'due_at',type:'datetime-local',value:deposit?.due_at},{name:'waived',type:'checkbox',value:deposit?.waived},reason])}>Set deposit requirement</button><button className="secondary" disabled={locked} onClick={()=>edit('Record payment','payment',[{name:'amount',type:'number',required:true},{name:'currency',required:true,value:deposit?.currency||application.currency||'USD'},{name:'paid_on',type:'date',required:true},{name:'method',options:choices(['CASH','BANK_TRANSFER','CARD','ONLINE','OTHER']),required:true},{name:'reference',label:'Transaction reference'},{name:'proof_id',label:'Payment proof document',options:documents}])}>Record payment</button></div>}
  {rows(data,'payments').map(p=><div className="record-card" key={text(p,'id')}><strong>{text(p,'ref')} · {text(p,'currency')} {text(p,'amount')}</strong><p>{label(text(p,'status'))} · {text(p,'paid_on')} · {label(text(p,'method'))} · {text(p,'reference')}</p>{editable&&!['CANCELLED','REFUNDED'].includes(text(p,'status'))&&(p.status!=='VERIFIED'||data.can_verify_payment===true)&&<button className="secondary" disabled={locked} onClick={()=>edit('Review payment status','payment_status',[{name:'status',options:choices(p.status==='PENDING'?['RECEIVED','CANCELLED']:p.status==='RECEIVED'?data.can_verify_payment?['VERIFIED','CANCELLED']:['CANCELLED']:data.can_verify_payment?['REFUNDED']:[]),required:true},{name:'proof_id',label:'Verified payment proof (optional replacement)',options:documents},reason],{id:p.id})}>Update payment status</button>}</div>)}
  <h3>Enrollment documents</h3>{(application.enrollment_requirements as string[]||[]).length>0&&<p>Required by this application workflow: {(application.enrollment_requirements as string[]).join(', ')}. Use the document kind or the same checklist title for supporting files.</p>}<p>Track CAS, CoE, I-20, LOA or other institution documents. Upload and verify their files in the application document checklist.</p>{editable&&<button className="secondary" disabled={locked} onClick={()=>edit('Record enrollment document','enrollment_document',[{name:'kind',options:choices(['CAS','COE','I20','LOA','OTHER']),required:true},{name:'number',required:true,label:'Institution document number'},{name:'issued_on',type:'date',required:true},{name:'expires_at',type:'datetime-local'},{name:'document_id',label:'Uploaded supporting document',options:documents,required:true}])}>Add enrollment document</button>}
  {rows(data,'enrollment_documents').map(d=><div className="record-card" key={text(d,'id')}><strong>{text(d,'kind')} · {text(d,'number')}</strong><p>{label(text(d,'status'))} · Issued {text(d,'issued_on')} {d.expires_at?`· Expires ${date(text(d,'expires_at'))}`:''}</p>{editable&&d.status!=='VERIFIED'&&<button className="secondary" disabled={locked} onClick={()=>edit('Verify enrollment document','verify_enrollment_document',[],{id:d.id})}>Verify document</button>}</div>)}
  <h3>Visa cases</h3>{user.role==='ADMIN'&&<VisaWorkflowEditor country={text(application,'destination')} saved={refresh}/>}{editable&&<button className="secondary" disabled={locked} onClick={()=>edit('Start visa attempt','visa_create',[{name:'workflow_id',label:'Destination visa workflow',required:true,options:workflows.filter(w=>String(w.country).toLowerCase()===text(application,'destination').toLowerCase()).map(w=>({id:text(w,'id'),name:`${w.country} · Version ${w.version}`}))}])}>Start visa attempt</button>}
  {rows(data,'visa_cases').map(c=><section className="record-card visa-case" key={text(c,'id')}><h3>{text(c,'ref')} · Attempt {text(c,'attempt_no')}</h3><p>{label(text(c,'state'))} · Workflow version {String((c.workflow as Row).version)} {c.appointment_at?`· Appointment ${date(text(c,'appointment_at'))}`:''}</p>{c.decision_reason?<p>Decision: {text(c,'decision_reason')}</p>:null}
   {editable&&!['APPROVED','REFUSED','WITHDRAWN'].includes(text(c,'state'))&&<div className="toolbar"><button className="secondary" disabled={locked} onClick={()=>edit('Update visa milestone / decision','visa_state',[{name:'state',label:'Next milestone or decision',options:choices(((c.workflow as Row).milestones as string[]).filter(s=>s!=='PREPARING')),required:true},reason],{case_id:c.id})}>Update visa state</button><button className="secondary" disabled={locked} onClick={()=>edit('Record visa appointment','visa_appointment',[{name:'appointment_at',type:'datetime-local',required:true},reason],{case_id:c.id})}>Appointment</button><button className="secondary" disabled={locked} onClick={()=>edit('Additional information request','visa_information',[{name:'title',required:true,label:'Requested document / evidence'},{name:'due_at',type:'datetime-local',required:true},reason],{case_id:c.id})}>Additional information</button><button className="secondary" disabled={locked} onClick={()=>edit('Record visa blocker','visa_blocker',[{name:'type',required:true},{name:'description',type:'textarea',required:true}],{case_id:c.id})}>Add blocker</button><button className="secondary" disabled={locked} onClick={()=>edit('Financial document metadata','financial_evidence',[{name:'document_id',label:'Supporting document',options:documents,required:true},{name:'kind',label:'Evidence type',required:true},{name:'holder',label:'Account / sponsor holder',required:true},{name:'amount',type:'number',required:true},{name:'currency',value:application.currency||'USD',required:true},{name:'statement_on',type:'date',required:true},{name:'expires_at',type:'datetime-local'}],{case_id:c.id})}>Add financial evidence</button></div>}
   <h4>Visa document checklist</h4>{rows(c,'documents').map(d=><p key={text(d,'id')}>{text(d,'title')} · {label(text(d,'status'))}</p>)}<p>Review and upload these files in the application document checklist above.</p>
   {rows(c,'financial_evidence').map(f=><div className="record-card" key={text(f,'id')}><strong>{text(f,'kind')} · {text(f,'holder')}</strong><p>{text(f,'currency')} {text(f,'amount')} · {label(text(f,'status'))} · Statement {text(f,'statement_on')}</p>{editable&&!['APPROVED','REFUSED','WITHDRAWN'].includes(text(c,'state'))&&<button className="secondary" disabled={locked} onClick={()=>edit('Review financial evidence','financial_review',[{name:'status',options:choices(['VERIFIED','REJECTED']),required:true},reason],{case_id:c.id,id:f.id})}>Review evidence</button>}</div>)}
   {rows(c,'blockers').filter(b=>!b.resolved_at).map(b=><p className="danger-text" key={text(b,'id')}>Open blocker: {text(b,'description')} · resolve in the application blockers queue.</p>)}
   <details><summary>Visa history</summary>{rows(c,'events').map(e=><p key={text(e,'id')}>{date(text(e,'created_at'))} · {label(text(e,'type'))} · {text(e,'reason')}</p>)}</details></section>)}
  <h3>Pre-departure, accommodation and arrival</h3>{editable&&['OFFER_ACCEPTED','ENROLLED'].includes(text(data,'state'))?<DepartureEditor key={revision} path={path} plan={rows(data,'predeparture')[0]||{}} defaults={((rows(data,'visa_cases')[0]?.workflow as Row)?.predeparture_checklist||[]) as string[]} saved={done} busyChanged={setSaving}/>:rows(data,'predeparture').map(p=><div key={text(p,'id')}><p>Accommodation: {text(p,'accommodation')}</p><p>Airport pickup: {text(p,'airport_pickup')}</p><p>Flight: {text(p,'flight_number')}</p>{['departure_at','arrival_at','arrived_at'].map(key=><p key={key}>{label(key)}: {p[key]?date(text(p,key)):'Not recorded'}</p>)}{rows(p,'checklist').map(item=><p key={text(item,'title')}>{text(item,'title')} · {label(text(item,'status'))}</p>)}</div>)}
  <h3>Final enrollment</h3>{rows(data,'enrollment').map(e=><p key={text(e,'id')}>Confirmed on {text(e,'enrolled_on')} · Institution reference {text(e,'institution_reference')}</p>)}{editable&&data.state==='OFFER_ACCEPTED'&&<button className="primary" disabled={locked} onClick={()=>edit('Confirm institution enrollment','enroll',[{name:'enrolled_on',type:'date',required:true},{name:'institution_reference',required:true},reason])}>Confirm final enrollment</button>}
 </section>;
}

function VisaWorkflowEditor({country,saved}:{country:string;saved:()=>Promise<void>}){
 const [show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget),lines=(name:string)=>String(fd.get(name)||'').split('\n').map(x=>x.trim()).filter(Boolean);try{await api('progression/workflows/','POST',{country,milestones:visaStates.filter(s=>!['BIOMETRICS_PENDING','INTERVIEW','ADMIN_PROCESSING'].includes(s)||fd.get(s)==='on'),required_documents:lines('documents'),predeparture_checklist:lines('predeparture'),financial_evidence_required:fd.get('financial')==='on'});setShow(false);await saved();}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <><button className="secondary" onClick={()=>setShow(!show)}>Configure destination visa workflow</button>{show&&<form className="inline-form" onSubmit={e=>void submit(e)}><h3>{country} · New visa workflow version</h3><p>Existing visa cases keep their saved workflow version.</p><p>Preparing → Ready → Submitted → decision</p>{['BIOMETRICS_PENDING','INTERVIEW','ADMIN_PROCESSING'].map(s=><label className="checkbox" key={s}>{label(s)}<input name={s} type="checkbox" defaultChecked={s!=='INTERVIEW'}/></label>)}<label>Required document titles (one per line)<textarea name="documents"/></label><label>Pre-departure checklist (one item per line)<textarea name="predeparture" defaultValue={'Confirm travel documents\nArrange accommodation\nArrange airport pickup\nConfirm flight\nReceive pre-departure briefing'}/></label><label className="checkbox">Financial evidence required<input name="financial" type="checkbox" defaultChecked/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>Save visa workflow version</button></form>}</>;
}

function DepartureEditor({path,plan,defaults,saved,busyChanged}:{path:string;plan:Row;defaults:string[];saved:()=>Promise<void>;busyChanged:(value:boolean)=>void}){
 const [checklist,setChecklist]=useState<Row[]>((plan.checklist||defaults.map(title=>({title,status:'PENDING'}))) as Row[]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);busyChanged(true);try{const payload:Row={action:'predeparture',checklist,reason:fd.get('reason')};for(const key of ['accommodation','airport_pickup','flight_number','notes'])payload[key]=fd.get(key);for(const key of ['departure_at','arrival_at','arrived_at'])if(fd.get(key))payload[key]=new Date(String(fd.get(key))+'+05:45').toISOString();await api(path,'POST',payload);await saved();}catch(e){setError(message(e));}finally{setBusy(false);busyChanged(false);}}
 return <form className="inline-form" onSubmit={e=>void submit(e)}>{checklist.map((item,i)=><label key={i}>{text(item,'title')}<select value={text(item,'status')} onChange={e=>setChecklist(items=>items.map((x,index)=>index===i?{...x,status:e.target.value}:x))}>{['PENDING','DONE','WAIVED'].map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label>)}<div className="form-grid">{['accommodation','airport_pickup','flight_number','notes'].map(key=><label key={key}>{label(key)}<input name={key} defaultValue={text(plan,key)}/></label>)}{['departure_at','arrival_at','arrived_at'].map(key=><label key={key}>{label(key)} (NPT)<input type="datetime-local" name={key} defaultValue={plan[key]?new Date(new Date(text(plan,key)).getTime()+345*60000).toISOString().slice(0,16):''}/></label>)}<label>Update reason<textarea name="reason" required/></label></div>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>Save departure / arrival details</button></form>;
}
