 'use client';
import {useState,useRef} from 'react';
import defaults from '@/lib/visitor-fields.json';
import {api,message,type Row} from '@/lib/api';
import {VisitorFields,type VisitorFormConfig} from './visitor-form';
export function VisitorFormEditor({qr,close,saved}:{qr:Row;close:()=>void;saved:()=>void}){
 const content=(qr.content||{}) as Row,form=(content.form||{}) as {title?:string;description?:string;fields?:Record<string,{visible?:boolean;required?:boolean}>};
 const [title,setTitle]=useState(form.title||'Visitor registration form'),[description,setDescription]=useState(form.description||'Please complete your main details. Fields marked * are required; all other fields are optional.'),[fields,setFields]=useState(form.fields||{}),[preview,setPreview]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);const paper=useRef<HTMLDivElement>(null);
 const config:VisitorFormConfig={title,description,fields:defaults.map(f=>({...f,...fields[f.name],required:f.locked||(fields[f.name]?.required??f.required),visible:f.locked||(fields[f.name]?.required??f.required)||(fields[f.name]?.visible??true)}))};
 function print(){const frame=document.createElement('iframe');frame.style.position='fixed';frame.style.width='0';frame.style.height='0';document.body.appendChild(frame);const doc=frame.contentDocument!;doc.open();doc.write('<!doctype html><html><head><title>Visitor registration form</title><style>body{font:12px Arial;color:#111;padding:20px}img{width:160px}fieldset{border:1px solid #bbb;margin:12px 0;padding:12px;break-inside:avoid}legend{font-weight:bold}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{display:block}.paper-answer{display:block;border-bottom:1px solid #aaa;height:25px}h1{font-size:22px}</style></head><body>'+paper.current!.innerHTML+'</body></html>');doc.close();const win=frame.contentWindow!;win.onafterprint=()=>frame.remove();const images=Array.from(doc.images);Promise.all(images.map(i=>i.decode().catch(()=>{}))).then(()=>{win.focus();win.print();});}
 async function save(){setBusy(true);setError('');try{await api(`qr/${qr.id}/`,'PATCH',{content:{...content,form:{title,description,fields}}});saved();close();}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <div className="modal-overlay"><section className="modal visitor-form-modal" role="dialog" aria-modal="true" aria-label="Edit visitor form"><div className="toolbar"><h2>Visitor registration form</h2><button className="secondary" onClick={close}>Close</button></div><div className="toolbar"><button className="secondary" onClick={()=>setPreview(!preview)}>{preview?'Edit form':'Preview form'}</button><button className="secondary" onClick={print}>Print blank form / save PDF</button><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save form'}</button></div><p>These settings apply to this registration QR. Name, mobile and consent always remain required. Preview and print include unsaved changes.</p>{!preview&&<><label>Form title<input value={title} maxLength={160} onChange={e=>setTitle(e.target.value)}/></label><label>Introduction<textarea value={description} maxLength={1000} onChange={e=>setDescription(e.target.value)}/></label>{config.fields.map(f=><div className="form-field-setting" key={f.name}><span>{f.label}</span><label className="checkbox"><input type="checkbox" checked={f.visible} disabled={f.locked||f.required} onChange={e=>setFields({...fields,[f.name]:{...fields[f.name],visible:e.target.checked}})}/>Show</label><label className="checkbox"><input type="checkbox" checked={f.required} disabled={f.locked} onChange={e=>setFields({...fields,[f.name]:{...fields[f.name],required:e.target.checked}})}/>Required</label></div>)}</>}{preview&&<div className="visitor-card"><h1>{title}</h1><p>{description}</p><VisitorFields config={config}/><label className="checkbox"><input type="checkbox" required/>I consent to recording my details and contact about my study plans. *</label><p>Preview only — answers are not submitted.</p></div>}<div ref={paper} hidden><img src="/logo-consman.jpg" alt="The Blessing Edu"/><h1>{title}</h1><p>{description}</p><VisitorFields config={config} blank/><p>□ I consent to recording my details and contact about my study plans. *</p><p>Visitor signature: ____________________ Date: ____________________</p><p>Office staff will verify the mobile number before registration.</p></div>{error&&<p className="error" role="alert">{error}</p>}</section></div>;
}
