 'use client';
import {useState} from 'react';
import {PhoneInput} from './phone-input';
import defaults from '@/lib/visitor-fields.json';
export type VisitorFormConfig={title:string;description:string;fields:(typeof defaults[number] & {visible?:boolean})[]};
export function VisitorFields({config,blank=false}:{config:VisitorFormConfig;blank?:boolean}){const [test,setTest]=useState('');return <>{Array.from(new Set(config.fields.map(f=>f.section))).map(section=><fieldset key={section}><legend>{section}</legend><div className="form-grid">{config.fields.filter(f=>f.section===section&&f.visible!==false&&(blank||f.name!=='english_score'||['IELTS','PTE','DUOLINGO','TOEFL','OTHER'].includes(test))&&(blank||f.name!=='english_other'||test==='OTHER')).map(f=><label key={f.name}>{f.label}{f.required?' *':' (optional)'}{blank?<span className="paper-answer"/>:f.kind==='phone'?<PhoneInput name={f.name} label={f.label} required={f.required}/>:f.kind==='select'?<select name={f.name} required={f.required} onChange={e=>{if(f.name==='english_test')setTest(e.target.value);}}><option value="">Choose an option</option>{f.options.map(o=><option key={o} value={o}>{({UNKNOWN:'Prefer to discuss',YES:'Yes',NO:'No',TAKEN:'Taken',PLANNED:'Planning to take',NOT_TAKEN:'Not given yet',WITHOUT_TEST:'I want to apply without IELTS/PTE',OTHER:'Another test',DUOLINGO:'Duolingo'} as Record<string,string>)[o]||o}</option>)}</select>:f.kind==='textarea'?<textarea name={f.name} required={f.required} maxLength={f.limit} rows={3}/>:<input name={f.name} type={f.kind} required={f.required} maxLength={f.limit} min={f.name==='passed_year'?1950:undefined} max={f.name==='passed_year'?2200:undefined}/>}</label>)}</div></fieldset>)}</>}
export function visitorAnswers(fd:FormData){const data:Record<string,unknown>={};for(const f of defaults)if(!['institute','degree_stream','grade_or_percent','passed_year','test_status','study_levels','english_score'].includes(f.name)&&!f.name.startsWith('test_')&&fd.has(f.name))data[f.name]=fd.get(f.name)||'';
 for(const n of ['previous_visa_refusal','best_contact_method'])if(!data[n])delete data[n];
 data.study_levels=fd.get('study_levels')?[fd.get('study_levels')]:[];data.preferred_countries=fd.get('preferred_country')?[fd.get('preferred_country')]:[];
 const education=['institute','degree_stream','grade_or_percent','passed_year'].some(n=>fd.get(n));data.education=education?[{level:fd.get('highest_education')||'Other',institute:fd.get('institute')||'Not specified',degree_stream:fd.get('degree_stream')||'',grade_or_percent:fd.get('grade_or_percent')||'',...(fd.get('passed_year')?{passed_year:Number(fd.get('passed_year'))}:{})}]:[];
 data.test_scores=['IELTS','PTE','TOEFL','DUOLINGO','SAT','GRE','GMAT','OTHER'].filter(t=>fd.get('test_'+t)).map(test=>({test,score:fd.get('test_'+test),status:fd.get('test_status')||'TAKEN'}));
 if(fd.get('test_status')&&!(data.test_scores as unknown[]).length)data.test_scores=[{test:'OTHER',score:'',status:fd.get('test_status')}];
 const selected=String(fd.get('english_test')||'');
 if(selected){data.test_scores=['NOT_TAKEN','WITHOUT_TEST'].includes(selected)?[{test:'OTHER',score:'',status:'NOT_TAKEN'}]:[{test:selected,score:fd.get('english_score')||'',status:'TAKEN'}];}else delete data.english_test;
 return data;}
