'use client';
import {PhoneInput} from '@/components/phone-input';
import {useEffect,useState,type FormEvent} from 'react';
import {api,message,type Row,type Masters,type User} from '@/lib/api';

export function WhatsAppQr({selected,masters,user,saved}:{selected:Row|null;masters:Masters;user:User;saved:(qr:Row)=>Promise<void>}){
 const content=(selected?.content||{}) as Row,design=(selected?.design||{}) as Row;
 const [phone,setPhone]=useState(String(content.phone||'')),[opening,setOpening]=useState(String(content.message||'')),[label,setLabel]=useState(String(selected?.label||'Office WhatsApp')),[branch,setBranch]=useState(Number(selected?.branch_id||user.branch_id)),[foreground,setForeground]=useState(String(design.foreground||'#047857')),[preview,setPreview]=useState(''),[error,setError]=useState(''),[previewError,setPreviewError]=useState(''),[busy,setBusy]=useState(false);
 const [staffId,setStaffId]=useState(String(content.staff_user_id||''));
 const appearance={...design,foreground,caption:'Scan to message on WhatsApp',frame:'caption',logo_shape:'circle'};
 useEffect(()=>{let active=true;const timer=setTimeout(async()=>{if(!phone){setPreview('');setPreviewError('');return;}try{const result=await api<{image:string}>('qr/preview/','POST',{...(selected?{id:selected.id}:{}),content_type:'WHATSAPP',content:{phone,message:opening},design:{...design,foreground,caption:'Scan to message on WhatsApp',frame:'caption',logo_shape:'circle'}});if(active){setPreview(result.image);setPreviewError('');}}catch(e){if(active){setPreview('');setPreviewError(message(e));}}},400);return()=>{active=false;clearTimeout(timer);};},[phone,opening,foreground,selected]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{const qr=await api<Row>(selected?`qr/${selected.id}/`:'qr/',selected?'PATCH':'POST',{label:label||'Office WhatsApp',branch_id:branch,content_type:'WHATSAPP',content:{phone,message:opening,staff_user_id:staffId?Number(staffId):null},design:appearance});await saved(qr);}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <div className="studio-grid"><form className="card record-card" onSubmit={e=>void submit(e)}><h2>{selected?'Edit WhatsApp QR':'Create WhatsApp QR'}</h2><p>Students scan this code to open the office, staff member or counsellor’s WhatsApp chat.</p><label>WhatsApp number (with country code)<PhoneInput label="WhatsApp number" value={phone} onChange={setPhone} required autoComplete="off"/></label><label>Office / staff / counsellor label<input value={label} onChange={e=>setLabel(e.target.value)} maxLength={160}/></label><label>Visible to staff<select value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="">Shared office WhatsApp</option>{masters.users.filter(u=>u.branch_id===branch).map(u=><option key={u.id} value={u.id}>{u.name} · {String(u.role)}</option>)}</select></label><label>Opening message (optional)<textarea value={opening} onChange={e=>setOpening(e.target.value)} placeholder="Hello, I would like to discuss my study plans." maxLength={1000}/></label><small>The message is filled in for the student. They choose whether to send it.</small>
  <details><summary>Print settings (optional)</summary>{masters.branches.length>1&&<label>Office branch<select value={branch} onChange={e=>setBranch(Number(e.target.value))}>{masters.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}<label>QR colour<input type="color" value={foreground} onChange={e=>setForeground(e.target.value)}/></label></details>
  {error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Generating and validating…':selected?'Save WhatsApp QR changes':'Generate WhatsApp QR'}</button></form><section className="card record-card"><h2>WhatsApp QR preview</h2>{preview?<img className="qr-preview" src={preview} alt="WhatsApp QR design preview"/>:<p>Enter a WhatsApp number to preview the code.</p>}{previewError&&<p className="error" role="alert">{previewError}</p>}{selected&&<><h3>Download and print</h3><div className="toolbar"><a className="secondary" href={`/api/v1/qr/${selected.id}/download/?format=png&size=1024`}>Download PNG</a><a className="secondary" href={`/api/v1/qr/${selected.id}/download/?format=svg`}>SVG</a>{['a4','a5','tent'].map(layout=><a className="secondary" key={layout} href={`/api/v1/qr/${selected.id}/download/?format=pdf&layout=${layout}`}>{layout.toUpperCase()} PDF</a>)}</div></>}<p>Use a number registered with WhatsApp. Students need an internet connection to start chatting.</p></section></div>;
}
