'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {api,message,type Row,type Masters,type User} from '@/lib/api';
import {PasswordInput} from './password-input';

export function WifiQr({selected,masters,user,saved}:{selected:Row|null;masters:Masters;user:User;saved:(qr:Row)=>Promise<void>}){
 const content=(selected?.content||{}) as Row,design=(selected?.design||{}) as Row;
 const [ssid,setSsid]=useState(String(content.ssid||'')),[password,setPassword]=useState(''),[security,setSecurity]=useState(String(content.security||'WPA')),[hidden,setHidden]=useState(Boolean(content.hidden)),[label,setLabel]=useState(String(selected?.label||'Office Wi-Fi')),[branch,setBranch]=useState(Number(selected?.branch_id||user.branch_id)),[foreground,setForeground]=useState(String(design.foreground||'#1e3a8a')),[logoShape,setLogoShape]=useState(String(design.logo_shape||'circle')),[preview,setPreview]=useState(''),[error,setError]=useState(''),[previewError,setPreviewError]=useState(''),[busy,setBusy]=useState(false);
 const network={ssid,security,hidden,...(password||security==='nopass'||!selected?{password}:{})};
 const appearance={...design,foreground,logo_shape:logoShape,caption:'Scan to join Wi-Fi',frame:'caption'};
 useEffect(()=>{let active=true;const timer=setTimeout(async()=>{if(!ssid||(!selected&&!password&&security!=='nopass')){setPreview('');setPreviewError('');return;}try{const result=await api<{image:string}>('qr/preview/','POST',{...(selected?{id:selected.id}:{}),content_type:'WIFI',content:{ssid,security,hidden,...(password||security==='nopass'||!selected?{password}:{})},design:{...design,foreground,logo_shape:logoShape,caption:'Scan to join Wi-Fi',frame:'caption'}});if(active){setPreview(result.image);setPreviewError('');}}catch(e){if(active){setPreview('');setPreviewError(message(e));}}},400);return()=>{active=false;clearTimeout(timer);};},[ssid,password,security,hidden,foreground,logoShape,selected]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{const qr=await api<Row>(selected?`qr/${selected.id}/`:'qr/',selected?'PATCH':'POST',{label:label||'Office Wi-Fi',branch_id:branch,content_type:'WIFI',content:network,design:appearance});await saved(qr);}catch(e){setError(message(e));}finally{setBusy(false);}}
 return <div className="studio-grid"><form className="card record-card" onSubmit={e=>void submit(e)}><h2>{selected?'Edit Wi-Fi QR':'Create Wi-Fi QR'}</h2><p>Students scan this printed code to join your office Wi-Fi, then scan the visitor registration QR.</p><label>Wi-Fi network name (SSID)<input value={ssid} onChange={e=>setSsid(e.target.value)} required maxLength={32} autoComplete="off"/></label>{security!=='nopass'&&<label>Wi-Fi password<PasswordInput value={password} onChange={e=>setPassword(e.target.value)} required={!selected} autoComplete="off"/>{selected&&<small>Leave blank to keep the saved password.</small>}</label>}
  <details><summary>Network settings (optional)</summary><label>Printed code label<input value={label} onChange={e=>setLabel(e.target.value)} maxLength={160}/></label>{masters.branches.length>1&&<label>Office branch<select value={branch} onChange={e=>setBranch(Number(e.target.value))}>{masters.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>}<label>Security<select value={security} onChange={e=>setSecurity(e.target.value)}><option value="WPA">WPA / WPA2 Personal (usual setting)</option><option value="WEP">WEP</option><option value="nopass">Open network (no password)</option></select></label><label className="checkbox">Hidden network<input type="checkbox" checked={hidden} onChange={e=>setHidden(e.target.checked)}/></label></details>
  <details><summary>QR appearance (optional)</summary><label>QR colour<input type="color" value={foreground} onChange={e=>setForeground(e.target.value)}/></label><label>Centre logo shape<select value={logoShape} onChange={e=>setLogoShape(e.target.value)}><option value="circle">Round</option><option value="rounded">Rounded square</option><option value="square">Square</option></select></label></details>
  {error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Generating and validating…':selected?'Save Wi-Fi QR changes':'Generate Wi-Fi QR'}</button></form>
  <section className="card record-card"><h2>Wi-Fi QR preview</h2>{preview?<img className="qr-preview" src={preview} alt="Wi-Fi QR design preview"/>:<p>Enter the network name and password to preview the code.</p>}{previewError&&<p className="error" role="alert">{previewError}</p>}{selected&&<><h3>Download and print</h3><div className="toolbar"><a className="secondary" href={`/api/v1/qr/${selected.id}/download/?format=png&size=1024`}>Download PNG</a><a className="secondary" href={`/api/v1/qr/${selected.id}/download/?format=svg`}>SVG</a>{['a4','a5','tent'].map(layout=><a className="secondary" key={layout} href={`/api/v1/qr/${selected.id}/download/?format=pdf&layout=${layout}`}>{layout.toUpperCase()} PDF</a>)}</div></>}<p>This QR connects to Wi-Fi. Keep the visitor registration QR printed beside it.</p></section></div>;
}
