# Generated by Django 6.0.8 on 2026-10-01 20:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0006_name_transliteration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('level', models.CharField(max_length=80)),
                ('duration_months', models.PositiveIntegerField(default=12)),
                ('requirements', models.TextField(blank=True)),
                ('english_requirements', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref', models.CharField(editable=False, max_length=24, unique=True)),
                ('state', models.CharField(default='DRAFT', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='crm.person')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('old', models.JSONField(default=dict)),
                ('new', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='admissions.application')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=30)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_tasks', to='admissions.application')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='crm.task')),
            ],
        ),
        migrations.CreateModel(
            name='Blocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blockers', to='admissions.application')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_blockers', to='crm.person')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('requirements', models.TextField(blank=True)),
                ('english_test', models.CharField(blank=True, max_length=20)),
                ('minimum_english_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimum_academic_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('availability', models.CharField(choices=[('OPEN', 'Open'), ('LIMITED', 'Limited'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admissions.campus')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admissions.course')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admissions.courseoffering'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(default='REQUESTED', max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='admissions.application')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_documents', to='crm.person')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=160)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(default='MANUAL', max_length=40)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deadlines', to='admissions.application')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_deadlines', to='crm.person')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admissions.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=160)),
                ('mime', models.CharField(max_length=80)),
                ('checksum', models.CharField(max_length=64)),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='admissions.document')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'start_date'), name='unique_intake_start')],
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='intake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admissions.intake'),
        ),
        migrations.CreateModel(
            name='OfferReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='CONDITIONAL', max_length=20)),
                ('conditions', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('status', models.CharField(default='RECEIVED', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='admissions.application')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admissions.document')),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eligibility', models.TextField(blank=True)),
                ('minimum_academic_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scholarships', to='admissions.courseoffering')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.JSONField(default=list)),
                ('levels', models.JSONField(default=list)),
                ('maximum_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('academic_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('courses', models.ManyToManyField(blank=True, to='admissions.course')),
                ('intakes', models.ManyToManyField(blank=True, to='admissions.intake')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admission_preference', to='crm.person')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('country', models.CharField(max_length=80)),
                ('website', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='unique_university_country')],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='admissions.university'),
        ),
        migrations.AddField(
            model_name='campus',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campuses', to='admissions.university'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=80)),
                ('version', models.PositiveIntegerField()),
                ('milestones', models.JSONField(default=list)),
                ('required_documents', models.JSONField(default=list)),
                ('offer_conditions', models.JSONField(default=list)),
                ('enrollment_requirements', models.JSONField(default=list)),
                ('visa_requirements', models.JSONField(default=list)),
                ('task_templates', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admissions.workflowtemplate'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('application', 'type'), name='unique_application_document_type'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='unique_document_version'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('course', 'campus', 'intake'), name='unique_course_campus_intake'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.CheckConstraint(condition=models.Q(('fee__gte', 0)), name='offering_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='scholarship',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='scholarship_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('university', 'name', 'level'), name='unique_university_course_level'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('university', 'name'), name='unique_university_campus'),
        ),
        migrations.AddConstraint(
            model_name='workflowtemplate',
            constraint=models.UniqueConstraint(fields=('destination', 'version'), name='unique_workflow_destination_version'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['state', 'created_at'], name='admissions__state_40dd7e_idx'),
        ),
    ]
