# Generated by Django 6.0.8 on 2026-10-01 10:44

import crm.models
import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('note_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SlaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('trigger', models.CharField(max_length=30, unique=True)),
                ('target_business_hours', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='channel',
            field=models.CharField(default='SYSTEM', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='corrects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='crm.activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='direction',
            field=models.CharField(default='INTERNAL', max_length=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='outcome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.branch'),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='channels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='consentrecord',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='shared_with_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='followup',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='followup',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='best_contact_method',
            field=models.CharField(default='CALL', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='person',
            name='highest_education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='hold_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='import_batch_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='import_row_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='next_action_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='next_action_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='preferred_countries',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='person',
            name='preferred_intake',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='person',
            name='preferred_university',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='person',
            name='previous_visa_refusal',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=7),
        ),
        migrations.AddField(
            model_name='person',
            name='source_file',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='study_levels',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='work_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='availability',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On leave'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='leave_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='max_open_leads',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='ACCESS', max_length=10)),
                ('reason', models.CharField(max_length=500)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('decided_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.person')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='MANAGER_QUEUE', max_length=20)),
                ('last_owner_id', models.PositiveIntegerField(default=0)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='crm.branch')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Kathmandu', max_length=60)),
                ('working_days', models.JSONField(default=crm.models.default_working_days)),
                ('open_time', models.TimeField(default=datetime.time(10, 0))),
                ('close_time', models.TimeField(default=datetime.time(17, 0))),
                ('holidays', models.JSONField(default=list)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='crm.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.source')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.campaign'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('storage_key', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='REQUESTED', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='crm.person')),
            ],
        ),
        migrations.CreateModel(
            name='EducationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=80)),
                ('institute', models.CharField(max_length=160)),
                ('degree_stream', models.CharField(blank=True, max_length=120)),
                ('grade_or_percent', models.CharField(blank=True, max_length=40)),
                ('passed_year', models.PositiveIntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education', to='crm.person')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160)),
                ('scope', models.CharField(max_length=200)),
                ('request_hash', models.CharField(max_length=64)),
                ('response', models.JSONField(null=True)),
                ('status_code', models.PositiveIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'scope'), name='unique_idempotency_key_scope')],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='lost_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.lostreason'),
        ),
        migrations.CreateModel(
            name='MergeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('field_choices', models.JSONField(default=dict)),
                ('moved_objects', models.JSONField(default=dict)),
                ('reversible_until', models.DateTimeField()),
                ('reversed_at', models.DateTimeField(null=True)),
                ('merged', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crm.person')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crm.person')),
            ],
        ),
        migrations.CreateModel(
            name='MfaDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_secret', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('last_counter', models.BigIntegerField(default=-1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.person')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(max_length=36)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.person')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlaTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(db_index=True)),
                ('satisfied_at', models.DateTimeField(null=True)),
                ('breached_at', models.DateTimeField(null=True)),
                ('access_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.accessrequest')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.branch')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sla_timers', to='crm.person')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.slarule')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.campaign')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='source_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.sourcedetail'),
        ),
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, to='crm.tag'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.CharField(default='NORMAL', max_length=10)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='crm.person')),
            ],
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=30)),
                ('score', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(default='PLANNED', max_length=20)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_scores', to='crm.person')),
            ],
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='crm.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'user'), name='unique_access_grant')],
            },
        ),
        migrations.CreateModel(
            name='DuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.CharField(max_length=10)),
                ('signals', models.JSONField(default=list)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crm.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crm.person')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person_a', 'person_b'), name='unique_duplicate_pair')],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_case', models.CharField(default='DOCUMENTATION', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to='crm.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'user'), name='unique_team_member')],
            },
        ),
    ]
