# Generated by Django 6.0.8 on 2026-10-01 11:27

from django.db import migrations, models


def backfill(apps,schema_editor):
    import re
    Person=apps.get_model('crm','Person')
    for person in Person.objects.all().iterator():
        name=re.sub(r'^(mr|mrs|ms|miss|dr)\.?\s+','', ' '.join(person.full_name.casefold().split()))
        Person.objects.filter(pk=person.pk).update(normalized_name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_audit_immutability'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.RunPython(backfill,migrations.RunPython.noop),
    ]
