# Generated by Django 6.0.8 on 2026-10-02 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_name_transliteration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Admin'), ('MANAGER', 'Branch Manager'), ('FRONTDESK', 'Frontdesk Officer'), ('COUNSELOR', 'Counselor'), ('DOCS', 'Documentation Staff'), ('FINANCE', 'Finance Staff'), ('MANAGEMENT', 'Management')], max_length=20),
        ),
        migrations.CreateModel(
            name='CounselingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('decisions', models.TextField(blank=True)),
                ('documents_checklist', models.JSONField(default=list)),
                ('pending_documents', models.TextField(blank=True)),
                ('next_step', models.CharField(blank=True, max_length=200)),
                ('service_taken', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='counseling_record', to='crm.person')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
