# Generated by Django 6.0.8 on 2026-10-02 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_counseling_suggestions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('UNIVERSITY', 'University'), ('COURSE', 'Course'), ('INTAKE', 'Intake')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'normalized_name'), name='unique_counseling_option')],
            },
        ),
    ]
