# Generated by Django 6.0.8 on 2026-10-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_counseling_option_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselingoption',
            name='kind',
            field=models.CharField(choices=[('COUNTRY', 'Country'), ('UNIVERSITY', 'University'), ('COURSE', 'Course'), ('INTAKE', 'Intake')], max_length=20),
        ),
    ]
