# Generated by Django 6.0.8 on 2026-10-03 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_completed_by(apps,schema_editor):
    FollowUp=apps.get_model('crm','FollowUp')
    AuditEvent=apps.get_model('crm','AuditEvent')
    alias=schema_editor.connection.alias
    for event in AuditEvent.objects.using(alias).filter(action='FOLLOWUP_COMPLETED',actor_id__isnull=False).order_by('at').iterator():
        followup_id=(event.new or {}).get('followup_id')
        if isinstance(followup_id,int) or isinstance(followup_id,str) and followup_id.isdigit():
            FollowUp.objects.using(alias).filter(pk=followup_id,completed_at__isnull=False,completed_by_id__isnull=True).update(completed_by_id=event.actor_id)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_counselingoption_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_completed_by,migrations.RunPython.noop),
    ]
