# Generated by Django 6.0.8 on 2026-10-01 10:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_lostreason_slarule_systempolicy_tag_activity_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='import-originals/')),
                ('mapping', models.JSONField(default=dict)),
                ('defaults', models.JSONField(default=dict)),
                ('status', models.CharField(default='STAGING', max_length=20)),
                ('counts', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField()),
                ('raw', models.JSONField(default=dict)),
                ('normalized', models.JSONField(default=dict)),
                ('result', models.CharField(default='STAGED', max_length=20)),
                ('errors', models.JSONField(default=list)),
                ('candidates', models.JSONField(default=list)),
                ('committed_person_updated_at', models.DateTimeField(null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='data_import.importbatch')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.person')),
            ],
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('file_hash', 'branch'), name='unique_import_file_branch'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_no'), name='unique_import_row'),
        ),
    ]
