# Generated by Django 6.0.8 on 2026-10-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='override_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
