# Generated by Django 6.0.8 on 2026-10-02 03:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_name_transliteration'),
        ('finance', '0001_initial'),
        ('progression', '0002_history_and_conditions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_on', models.DateField()),
                ('transaction_reference', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='finance.institutioncommission')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_kind', models.CharField(max_length=30)),
                ('object_id', models.CharField(max_length=40)),
                ('action', models.CharField(max_length=60)),
                ('old', models.JSONField(default=dict)),
                ('new', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.branch')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=80)),
                ('content', models.BinaryField()),
                ('checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_files', to='finance.commissionreceipt')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_files', to='finance.expense')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_files', to='progression.payment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='progression.payment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='commissionreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='commission_receipt_positive'),
        ),
        migrations.AddIndex(
            model_name='financeevent',
            index=models.Index(fields=['object_kind', 'object_id', 'created_at'], name='finance_fin_object__05b2f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='financefile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('commission_receipt__isnull', True), ('expense__isnull', True), ('payment__isnull', False)), models.Q(('commission_receipt__isnull', True), ('expense__isnull', False), ('payment__isnull', True)), models.Q(('commission_receipt__isnull', False), ('expense__isnull', True), ('payment__isnull', True)), _connector='OR'), name='finance_file_one_owner'),
        ),
    ]
