# Generated by Django 6.0.8 on 2026-10-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financial_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='issued_snapshot',
            field=models.JSONField(default=dict),
        ),
    ]
