'use client';
import defaultFields from '@/lib/visitor-fields.json';
import {VisitorFields,visitorAnswers,type VisitorFormConfig} from '@/components/visitor-form';
import {PhoneInput} from '@/components/phone-input';
import {use,useEffect,useRef,useState,type FormEvent} from 'react';
import Image from 'next/image';
type Result={id:string;resume_token:string;verified?:boolean;status:string;send_failed?:boolean;message?:string;phone?:string;attempts_left?:number;resend_after?:number};
type Configuration={form:VisitorFormConfig;active:boolean;branch:string;turnstile_site_key:string;development_bypass:boolean;whatsapp_available:boolean;message:string};
type Turnstile={render:(el:HTMLElement,options:Record<string,unknown>)=>string;remove:(id:string)=>void;reset:(id:string)=>void};
export default function Registration({params}:{params:Promise<{code:string}>}){
 const {code}=use(params),[config,setConfig]=useState<Configuration|null>(null),[result,setResult]=useState<Result|null>(null),[complete,setComplete]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[token,setToken]=useState(''),[cooldown,setCooldown]=useState(0),[channel,setChannel]=useState('SMS');const widget=useRef<HTMLDivElement>(null),widgetId=useRef(''),key=useRef(''),answerBody=useRef('');
 const storage='consman-intake:'+code;
 async function request(path:string,method='GET',body?:unknown,credentials?:Result,idempotencyKey?:string){const r=await fetch('/api/public/'+path,{method,credentials:'omit',headers:{'Content-Type':'application/json',...(credentials?{'X-Resume-Token':credentials.resume_token}:{}),...(method!=='GET'?{'Idempotency-Key':idempotencyKey||crypto.randomUUID()}: {})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.message+(data.fields?' '+JSON.stringify(data.fields):'')),{details:data});return data;}
 useEffect(()=>{let active=true;request('qr/'+code+'/').then(async c=>{if(!active)return;c.form ||= {title:'Visitor registration form',description:'Fields marked * are required. Other details are optional.',fields:defaultFields};setConfig(c);if(c.active&&!c.development_bypass&&!c.turnstile_site_key)setError('Phone verification is temporarily unavailable. Please ask the front desk for help.');setToken(c.development_bypass?'development':'');setChannel(c.whatsapp_available?'WHATSAPP':'SMS');const saved=localStorage.getItem(storage);if(saved){try{const credentials=JSON.parse(saved) as Result,resumed=await request(`intake/submissions/${credentials.id}/resume/`,'GET',undefined,credentials);if(active){setResult({...credentials,...resumed});setCooldown(resumed.resend_after||0);setComplete(['VERIFIED','PROCESSED'].includes(resumed.status));}}catch{localStorage.removeItem(storage);}}}).catch(e=>setError(e.message));return()=>{active=false;};},[code,storage]);
 useEffect(()=>{if(!config?.turnstile_site_key||config.development_bypass||result)return;const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;script.onload=()=>{const t=(window as Window & {turnstile?:Turnstile}).turnstile;if(widget.current&&t)widgetId.current=t.render(widget.current,{'sitekey':config.turnstile_site_key,'size':'flexible','response-field':false,'callback':setToken,'expired-callback':()=>setToken(''),'error-callback':()=>{setToken('');setError('The verification check could not load. Check your connection and reload this page.');}});};script.onerror=()=>setError('The verification check could not load. Check your connection and reload this page.');document.head.appendChild(script);return()=>{const t=(window as Window & {turnstile?:Turnstile}).turnstile;if(widgetId.current)t?.remove(widgetId.current);script.remove();};},[config,result]);
 useEffect(()=>{if(!cooldown)return;const timer=setTimeout(()=>setCooldown(n=>Math.max(0,n-1)),1000);return()=>clearTimeout(timer);},[cooldown]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const fd=new FormData(e.currentTarget);fd.delete('cf-turnstile-response');try{const answers={...visitorAnswers(fd),website:fd.get('website')||'',code,channel,consent:fd.get('consent')==='on',consent_channels:[channel,'CALL'],turnstile_token:token};const signature=JSON.stringify({...answers,turnstile_token:undefined});if(answerBody.current!==signature){answerBody.current=signature;key.current=crypto.randomUUID();}const data=await request('intake/submissions/','POST',answers,undefined,key.current);setResult(data);localStorage.setItem(storage,JSON.stringify({id:data.id,resume_token:data.resume_token}));setCooldown(60);}catch(e){setError((e as Error).message);if(!config?.development_bypass){setToken('');const t=(window as Window & {turnstile?:Turnstile}).turnstile;if(widgetId.current)t?.reset(widgetId.current);}}finally{setBusy(false);}}
 async function verify(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await request(`intake/submissions/${result!.id}/otp/verify/`,'POST',{code:new FormData(e.currentTarget).get('otp')},result!);setComplete(true);localStorage.removeItem(storage);}catch(e){setError((e as Error).message);const d=(e as Error & {details?:Partial<Result>}).details;if(d)setResult(r=>r?{...r,...d}:r);}finally{setBusy(false);}}
 async function resend(phone?:string){setBusy(true);setError('');try{const data=await request(`intake/submissions/${result!.id}/${phone?'phone/':'otp/resend/'}`,'POST',{channel,...(phone?{phone}:{})},result!);setResult({...result!,...data});setCooldown(60);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <main className="visitor-page"><section className="visitor-card"><Image src="/logo-consman.jpg" alt="ConsMan — The Blessing Edu" width={240} height={130} priority/>{!config?<p>Opening registration…</p>:!config.active?<><h1>Registration unavailable</h1><p>{config.message}</p></>:complete?<><h1>Thank you</h1><p>Our team will contact you about your next steps.</p></>:result?<><h1>Your details are saved</h1><p>Enter the six-digit code sent to your phone. Your answers are safe if delivery fails.</p>{result.send_failed&&<p className="notice">The code could not be sent. Retry when delivery is available or ask the front desk to verify your number.</p>}<p>{result.attempts_left??5} attempts remaining</p><form onSubmit={verify}><label>Verification code<input name="otp" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required/></label><button className="primary" disabled={busy||result.attempts_left===0}>Verify number</button></form><label>Delivery channel<select value={channel} onChange={e=>setChannel(e.target.value)}><option value="SMS">SMS</option>{config.whatsapp_available&&<option value="WHATSAPP">WhatsApp</option>}</select></label><button className="secondary" disabled={busy||cooldown>0} onClick={()=>void resend()}>{cooldown?`Resend in ${cooldown}s`:'Resend code'}</button><details><summary>Correct phone number</summary><form onSubmit={e=>{e.preventDefault();void resend(String(new FormData(e.currentTarget).get('phone')));}}><label>Corrected phone<PhoneInput name="phone" label="Corrected phone" defaultValue={result?.phone||''} required/></label><p>You may correct your number twice.</p><button className="secondary" disabled={busy||cooldown>0}>Save number and resend</button></form></details></>:<><div className="eyebrow">THE BLESSING EDU · {config.branch}</div><h1>{config.form.title}</h1><p>{config.form.description}</p><form onSubmit={submit}><VisitorFields config={config.form}/><div className="form-grid"><label>Delivery channel<select value={channel} onChange={e=>setChannel(e.target.value)}><option value="SMS">SMS</option>{config.whatsapp_available&&<option value="WHATSAPP">WhatsApp</option>}</select></label><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="checkbox span-2"><input name="consent" type="checkbox" required/>I agree to The Blessing Edu recording my details and contacting me about my study plans by my selected channel and phone.</label></div><div ref={widget}/>{config.development_bypass&&<small>Local development verification is enabled.</small>}<button className="primary" disabled={busy||!token}>{busy?'Saving your details…':'Save and verify number'}</button></form></>}{error&&<p className="error" role="alert">{error}</p>}<p className="login-note">Need help? Ask our front desk. Your registration can be verified by call.</p></section></main>;
}
