# Generated by Django 6.0.8 on 2026-10-01 10:44

import django.db.models.deletion
import qr.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0002_lostreason_slarule_systempolicy_tag_activity_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=qr.models.short_code, editable=False, max_length=24, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('content_type', models.CharField(default='REGISTRATION', max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('design', models.JSONField(default=dict)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('asset_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.branch')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QRAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('png', models.FileField(upload_to='qr-assets/')),
                ('svg', models.FileField(upload_to='qr-assets/')),
                ('design', models.JSONField(default=dict)),
                ('payload', models.TextField()),
                ('decode_passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='qr.qrcode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('qr', 'version'), name='unique_qr_asset_version')],
            },
        ),
    ]
